### ISSUE TITLE
Research adding type transformer support (String -> T?)

### ISSUE THREAD

**Issue by drmohundro** [drmohundro/SWXMLHash#10]
It'd be nice to have API support so that values can be converted into types (like `(String -> T?)`).

**Comment by tkrajacic** [comment]
I was looking into this recently (just don't have the time to actually implement it).
I think https://github.com/Hearst-DD/ObjectMapper has it done quite nicely.
It's worth having a look there.

**Comment by drmohundro** [comment]
Nice, I hadn't seen this library yet. Definitely looks like an option.

**Comment by ncreated** [comment]
@drmohundro I did kind of type conversion on top of `SWXMLHash` in one of my projects. I found a bit of time to integrate it with [my fork of `SWXMLHash`](https://github.com/ncreated/SWXMLHash). Have a look at my API. If you like it, I can do a PR :gift: .

Anyway, thanks a lot for this library :+1:.

--

An example from my `README.md` (I covered much more in my [SWXMLHashSpecs.swift](https://github.com/ncreated/SWXMLHash/blob/master/Tests/SWXMLHashSpecs.swift)):

```xml
<root>
  <books>
    <book>
      <title>Book A</title>
      <price>12.5</price>
      <year>2015</year>
    </book>
    <book>
      <title>Book B</title>
      <price>10</price>
      <year>1988</year>
    </book>
    <book>
      <title>Book C</title>
      <price>8.33</price>
      <year>1990</year>
      <amount>10</amount>
    </book>
  <books>
</root>
```
The `Book` struct implements `XMLIndexerDeserializable`:

```swift
struct Book: XMLIndexerDeserializable {
    let title: String
    let price: Double
    let year: Int
    let amount: Int?
    
    static func deserialize(node: XMLIndexer) throws -> Book {
        return try Book(
            title: node["title"].value(),
            price: node["price"].value(),
            year: node["year"].value(),
            amount: node["amount"].value()
        )
    }
}
```

And the below returns array of `Book` structs:

```swift
let books: [Book] = try xml["root"]["books"]["book"].value()
```

<img src="https://raw.githubusercontent.com/ncreated/SWXMLHash/assets/types-conversion%402x.png" width="600" alt="Types Conversion" />

**Comment by drmohundro** [comment]
@ncreated - nice, I'll definitely check it out!

**Comment by drmohundro** [comment]
@ncreated - I finally got a chance to check this out and it looks great to me. Definitely go ahead and open a pull request for it. I'll probably have a few minor questions/suggestions, but I do want to see this get merged in, it looks great!

**Comment by ncreated** [comment]
@drmohundro Thanks :wink:. Feel free to comment/suggest on the PR I just opened.

**Comment by drmohundro** [comment]
So I merged this right after installing the latest Xcode which means that Quick/Nimble aren't compiling for me. I'll either pull down the last version of Xcode or hold off on getting a CocoaPods/Carthage build for when Quick/Nimble get updated - it shouldn't be long. In the meantime, I'll see about getting a FAQ section added to the README and updating the CHANGELOG.

For anyone who is interested in using this feature, it is in master now.

**Comment by drmohundro** [comment]
:point_up: the above issue wasn't actually an Xcode issue, but something related to targeting `tvOS`... apparently been an issue for a little while now. Either way, I should be able to get a release out shortly.

**Comment by drmohundro** [comment]
This is out with `2.2.0` - thanks again all for your help!

**Comment by jwilson85** [comment]
I'm getting an error when trying to implement this. Sorry if I'm not doing it right. The error I'm getting is. 
/ViewController.swift:97:24: Cannot invoke initializer for type 'ViewController.Book' with an argument list of type '(title: _, type: _, id: _, mount: _)'

**Comment by drmohundro** [comment]
@jwilson85 could you include the full source so that I could see if I can reproduce the problem? Thanks!

**Comment by jwilson85** [comment]
This seems to work in the playground but not when I copy it into a viewController.  I'm trying to use AlamoFire and get back XML then use the deserialize method. I don't have the code that gave me that error anymore now I just get. a build error saying that I'm not handling the try with a throw. Is there an example of how I would use this in conjunction with AlamoFire

**Comment by jwilson85** [comment]
I think i'll just use KVC since I don't really understand what's happening here

**Comment by drmohundro** [comment]
I'm going to add a TODO to get an example of using AlamoFire with SWXMLHash - I know of many cases where people are using it, but I don't have a code example off hand that I can provide.

**Comment by jwilson85** [comment]
Cool, that would be helpful I wasn't understanding how  the function
desterilize was getting called when what looked to me was the struct was
the only thing getting invoked.

Sincerely,
Jeremy A Wilson
720-882-2617
jaywdice@gmail.com

**Comment by ncreated** [comment]
@drmohundro I'm using `SWXMLHash` with `Alamofire` in my project. What they suggest on `Alamofire's` website, is to create generic response serializer. I did one for `SWXMLHash` and the deserializer that I authored:

```swift
import SWXMLHash
import Alamofire


extension Alamofire.Request {
    public func responseObjectForKeyPath<T: XMLIndexerDeserializable>(keyPath: String, completionHandler: (NSURLRequest?, NSHTTPURLResponse?, Result<T>) -> ()) -> Self {
        let responseSerializer = GenericResponseSerializer<T> { request, response, data in
            guard let data = data else {
                let error = Error.errorWithCode(.DataSerializationFailed, failureReason: "Received empty response")
                return .Failure(nil, error)
            }
            
            do {
                let xml = SWXMLHash.parse(data)
                let modelXML = try xml.byKeyPath(keyPath)
                let model = try T.deserialize(modelXML)
                return .Success(model)
            } catch let error {
                return .Failure(data, error)
            }
        }
        
        return response(responseSerializer: responseSerializer, completionHandler: completionHandler)
    }
    
    public func responseArrayForKeyPath<T: XMLIndexerDeserializable>(keyPath: String, completionHandler: (NSURLRequest?, NSHTTPURLResponse?, Result<[T]>) -> ()) -> Self {
        let responseSerializer = GenericResponseSerializer<[T]> { request, response, data in
            guard let data = data else {
                let error = Error.errorWithCode(.DataSerializationFailed, failureReason: "Received empty response")
                return .Failure(nil, error)
            }
            
            do {
                var models = [T]()
                let xml = SWXMLHash.parse(data)
                let collection = try xml.byKeyPath(keyPath)

                for modelXML in collection {
                    let model = try T.deserialize(modelXML)
                    models.append(model)
                }

                return .Success(models)
            } catch XMLIndexer.Error.Key(let key) {
                if let lastKey = keyPath.componentsSeparatedByString(".").last where key == lastKey {
                    return .Success([]) // collection is empty
                }
                return .Failure(data, XMLIndexer.Error.Key(key: key))
            } catch let error {
                return .Failure(data, error)
            }
        }
        
        return response(responseSerializer: responseSerializer, completionHandler: completionHandler)
    }
}

extension XMLIndexer {
    public func byKeyPath(keyPath: String) throws -> XMLIndexer {
        return try byKeyPath(keyPath.componentsSeparatedByString("."))
    }
    
    public func byKeyPath(keyPath: [String]) throws -> XMLIndexer {
        if keyPath.isEmpty { return self }
        
        let firstKey = keyPath[0]
        let otherKeys = Array(keyPath[1..<keyPath.count])
        return try self.byKey(firstKey).byKeyPath(otherKeys)
    }
}
```

My `APIService` provides two methods, one for fetching objects and one for collections:

```swift
    func fetchObjectFromEndpoint<T: XMLIndexerDeserializable>(endpoint: APIEndpoint, callback: (Result<T>) -> ()) -> Request {
        return endpoint.requestWithManager(manager).responseObjectForKeyPath(nodePath) { (_, _, result: Result<T>) in
            callback(result)
        }
    }
    
    func fetchCollectionFromEndpoint<T: XMLIndexerDeserializable>(endpoint: APIEndpoint, callback: (Result<[T]>) -> ()) -> Request {
        let nodePath = endpoint.responseNodePath
        return endpoint.requestWithManager(manager).responseArrayForKeyPath(nodePath) { (_, _, result: Result<[T]>) in
            callback(result)
        }
    }
```

which I can use this way:

```swift
// `Museum` is a struct implementing `XMLIndexerDeserializable`

services.api.fetchCollectionFromEndpoint(.Museums) { (result: Result<[Museum]>) in
    switch result {
        case .Success(let museums):
            print("museums: \(museums)\n")
        case .Failure(_, let error):
            print("\(error)\n")
    }
}
```

I'm using `Alamofire` 2.0 and my custom version of `SWXMLHash` which is slightly different from my fork. But as far as I see, above should also apply to the current version of `SWXMLHash`.

--

I might turn this into an example of how to use `SWXMLHash` with `Alamofire` one day, but I have no time for this currently 😰.
