### ISSUE TITLE
is there an xcode 8 Swift 3.0 version

### ISSUE THREAD

**Issue by telcosolutions** [drmohundro/SWXMLHash#100]
SWXMLHash has worked great for us but now loaded xoode 8 and using swift 3.0.

**Comment by drmohundro** [comment]
Yep, I just released version 3.0.0 last week (actually 3.0.2). It should work with CocoaPods or Carthage. In addition, `master` is tracking the latest as well.

**Comment by a9austin** [comment]
Thanks!
