### ISSUE TITLE
XML only partially parsed and returned

### ISSUE THREAD

**Issue by larsblumberg** [drmohundro/SWXMLHash#102]
```
import SWXMLHash

let xml = SWXMLHash.parse("<?xml version=\"1.0\"?><s:Envelope xmlns:s=\"http://schemas.xmlsoap.org/soap/envelope/\" s:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\"><s:Body><u:GetTransportInfoResponse xmlns:u=urn:schemas-upnp-org:service:AVTransport:1\"><CurrentTransportState>PAUSED_PLAYBACK</CurrentTransportState><CurrentTransportStatus>OK</CurrentTransportStatus><CurrentSpeed>1</CurrentSpeed></u:GetTransportInfoResponse></s:Body></s:Envelope>")

// Following line prints `nil` although node is present
print(xml["s:Envelope"]["s:Body"]["u:GetTransportInfoResponse"]["CurrentTransportState"].element)

// Children of s:Body have been ignored
print(xml.description)
```

prints

```
nil
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"><s:Body></s:Body></s:Envelope>
```

thus leaving out all children within `s:Body` tag.

If you remove `xmlns:u=urn:schemas-upnp-org:service:AVTransport:1\"` from `s:Body`, document is properly parsed.

**Comment by larsblumberg** [comment]
Just realized that the XML is invalid, there's a missing `"` at the beginning of the attribute value for `xmlns:u`. Unfortunately this xml is not returned by us.

**Comment by drmohundro** [comment]
@larsblumberg sorry to hear that - I know of a few cases where people have done some string modification on bad XML prior to it being parsed by SWXMLHash. It is very clearly a hack and extremely brittle, but at least some people are doing it. If you're able to work with the party that is generating the XML, though, that would be best I'm sure.

**Comment by larsblumberg** [comment]
Thanks for your feedback, I'm getting the response from a web service and as you suggest we now do string manipulation prior to handing it over to swxmlhash.

What's your opinion on adding a _strict mode_ parameter to the parsing methods? It could default to true but when false it would ignore missing quotation marks or missing closing tags.

Right now the parser creates semi parsed models as in my case without letting me know, it took me a while to understand that the document wasn't valid. I would prefer the parser to return _nil_ instead if the XML document wasn't valid.

I understand if this is however beyond the scope of this library.

**Comment by drmohundro** [comment]
I like the idea of validating the XML ahead of time because it is a lot easier when an "invalid XML" error is thrown instead of dealing with partially parsed XML; however, based on my limited research, I didn't see anything related to doing this with `NSXMLParser` (which is what SWXMLHash is based on). SWXMLHash will have any limitations that `NSXMLParser` has.

I'll keep it in mind and will keep thinking about possible options to handle it, though.
