### ISSUE TITLE
Error: Enum case 'Some' not found in type 'XMLIndexer'

### ISSUE THREAD

**Issue by eligreg** [drmohundro/SWXMLHash#104]
After an Alamofire request, retrieving the string response (a String of XML), this code:

```
if let xmlstr = response.result.value, let xml = SWXMLHash.parse(xmlstr) { 
    // 
}
```

Throws this error:

> SWXMLHash Enum case 'Some' not found in XMLIndexer

Using XCode 8, Swift 3, Cocoapods 

> pod 'SWXMLHash', '~> 3.0.0'

Any ideas as to what is going on? Thanks in advance!

**Comment by drmohundro** [comment]
@eligreg were you able to resolve this? I noticed you closed the issue.
