### ISSUE TITLE
Alamofire + Swift 3 

### ISSUE THREAD

**Issue by PanMluvci** [drmohundro/SWXMLHash#111]
Hi there. Can u provide me working Alamofire + SWXMLHash code? In Swift 2 I had this.

```
Alamofire.request(.GET, "https://example.com/info.php", headers: headers)
            .response { (request, response, data, error) in
                
                let xml = SWXMLHash.parse(data!)
                let e21Time = xml["tabless"]["tables"][0]["UPDATE_TIME"].element?.text
}
```

**Comment by drmohundro** [comment]
The API hasn't really changed between version 2 and version 3 - the main difference is that SWXMLHash 3.0 was released which specifically targets Swift 3.0. All you should have to do is update to the latest version of SWXMLHash. How are you targeting SWXMLHash right now? Most people seem to be using CocoaPods or Carthage - you should be able to just change the version from 2.0 to 3.0.

**Comment by PanMluvci** [comment]
Well libraries are working OK... but I can't to do this
`let xml = SWXMLHash.parse(data!)`
with swift 3

**Comment by drmohundro** [comment]
What sort of error are you getting? That should work just fine assuming `data` is an instance of either `String` or `Data`. One thing to note is that, in Swift 2, data was of type `NSData` but in Swift 3 it is now just `Data`. It is the same underlying type, but it changed names in Swift 3. Maybe that is what you're running into?

**Comment by PanMluvci** [comment]
Oh... my bad ... this is solution. I did not saw that Alamofire does not contain (response, data, error) parameters anymore but just (response) so... this is the solution.
`let xml = SWXMLHash.parse(response.data!) `
Thank you for your time :-)

**Comment by drmohundro** [comment]
Gotcha! Well no worries! I'll go ahead and close this issue then. Thanks for updating the ticket!
