### ISSUE TITLE
withAttr should be withAttribute to align with Swift verbose naming conventions

### ISSUE THREAD

**Issue by DonSwet** [drmohundro/SWXMLHash#116]
Apple's argument for this one lies in AutoComplete. It's actually a good argument which also encourages legibility.

**Comment by drmohundro** [comment]
I agree - if I remember correctly, I added that method before some of the naming conventions were even added (pre Swift 1.0 release). I created #84 to track API changes, so it'd be nice to get this added in prior to the 4.0 release and deprecate the old method.

By the way, I'd welcome any other API thoughts or suggestions you might have!

**Comment by drmohundro** [comment]
FYI, this was resolved with `4.0.0` and #133. Thanks!
