### ISSUE TITLE
Is that repo still work nicely in Swift 3?.

### ISSUE THREAD

**Issue by Bat-Orshikh** [drmohundro/SWXMLHash#121]
I used your repo in my app 👍. Now I want to update app into swift 3. Is that repo still work nicely in Swift 3?.

**Comment by drmohundro** [comment]
Yes, SWXMLHash works fine with Swift 3.0 - in fact, if you check out the [CHANGELOG](https://github.com/drmohundro/SWXMLHash/blob/master/CHANGELOG.md#v300---301-september-13-2016) you'll see that Swift 3.0 support was officially added in version 3.0 back in September.

**Comment by Bat-Orshikh** [comment]
Hi agian!. I faced a problem with install version 3.0
![Uploading Screen Shot 2017-02-06 at 8.48.50 PM.png…]()
In my podlock file.
PODS:
  - SWXMLHash (2.4.0)

DEPENDENCIES:
  - SWXMLHash

SPEC CHECKSUMS:
  CZPicker: df3d8d0511595b7cd2f032263c82c611d45a9b8e
  SSZipArchive: bab21000ee11b7ba68d5880bcd87d80e4eb93e65
  SWXMLHash: 507397103325f140863d09040c04ae14a49a16cb

PODFILE CHECKSUM: b28fbf9680fbee5baae7c2fe19a5d86dfc0078b0

COCOAPODS: 1.2.0

**Comment by drmohundro** [comment]
What does your `Podfile` look like? Have you tried running `pod repo update` as the error indicates? The output says that it is installing version `2.4.0` which *does not* work on Swift 3.0 - only SWXMLHash 3+ works on Swift 3.0.

**Comment by Bat-Orshikh** [comment]
Thanks for your quick response and help. I fixed my problem with your suggestion "pod repo update". Then I installed SWXMLHash (3.0.4). Thanks for you. 👍

**Comment by drmohundro** [comment]
Great - glad you got it working!
