### ISSUE TITLE
SwiftPM badge and install section are missing

### ISSUE THREAD

**Issue by TofPlay** [drmohundro/SWXMLHash#123]
On your `README.md` [![SwiftPM Compatible](https://img.shields.io/badge/SwiftPM-Compatible-brightgreen.svg)](https://goo.gl/E01ufX) and install section for SwiftPM is missing.

[SwiftPM](https://goo.gl/E01ufX) is Swift's official package manager. In the near future it will replace Carthage and CocoaPods.

Here some articles about SwiftPM:
* [An Introduction to the Swift Package Manager](https://goo.gl/byiOc6)
* [Swift Dependency Management for iOS](https://goo.gl/7eaz1A)
* [Getting Started with Swift Package Manager (SwiftPM)](https://goo.gl/rCHeQU)
* [Swift.org: Package Manager](https://goo.gl/E01ufX)

**Comment by drmohundro** [comment]
Good call, I do need to update the docs to indicate that!

**Comment by drmohundro** [comment]
Closing this as there is SPM documentation now.
