### ISSUE TITLE
Compilation Error cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by legalimpurity** [drmohundro/SWXMLHash#125]
I have the following networking class 

typealias successXMLHandler = (_ obj:XMLIndexer?)->Void

if let xmlg : String = String(data: dataa, encoding: String.Encoding.utf8)
                    {
                        if let xml = SWXMLHash.parse(xmlg) as? XMLIndexer
                        {
                            successXMLHandler(xml)
                        }
                    }
I am using alomofire.

**Comment by drmohundro** [comment]
Which line in the above is getting the compilation error?

**Comment by legalimpurity** [comment]
successXMLHandler(xml)

**Comment by legalimpurity** [comment]
My bad

**Comment by drmohundro** [comment]
I guess you got it working? That's good!
