### ISSUE TITLE
This node is invalid: 

### ISSUE THREAD

**Issue by n1tesh** [drmohundro/SWXMLHash#126]
I'm fetching Google Contacts and I'm trying to Deserialize the object using 'SWXMLHash' but when I try to Deserialize it gives error
>This node is invalid: 

Data format

    <feed gd:etag="W/"DEENSH0_fit7I2A9XR9QEk8.""
        xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
        xmlns="http://www.w3.org/2005/Atom"
        xmlns:gContact="http://schemas.google.com/contact/2008"
        xmlns:batch="http://schemas.google.com/gdata/batch"
        xmlns:gd="http://schemas.google.com/g/2005">
        <id>cdsadsdsoolndasdsdidsadtmadasns@gmail.com</id>
        <updated>2017-04-26T17:11:39.346Z</updated>
        <category scheme="http://schemas.google.com/g/2005#kind" term="http://schemas.google.com/contact/2008#contact"></category>
        <title>Nitesh's Contacts</title>
        <link rel="alternate" type="text/html" href="http://www.google.com/"></link>
        <link rel="http://schemas.google.com/g/2005#feed" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin"></link>
        <link rel="http://schemas.google.com/g/2005#post" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin"></link>
        <link rel="http://schemas.google.com/g/2005#batch" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin/batch"></link>
        <link rel="self" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin?max-results=10000"></link>
        <author>
            <name>Nitesh</name>
            <email>cdsadsdsoolndasdsdidsadtmadasns@gmail.com</email>
        </author>
        <generator uri="http://www.google.com/m8/feeds" version="1.0">Contacts</generator>
        <openSearch:totalResults>4797</openSearch:totalResults>
        <openSearch:startIndex>1</openSearch:startIndex>
        <openSearch:itemsPerPage>10000</openSearch:itemsPerPage>
        <entry gd:etag=""Q3wzeDsadssaVSLysdadst7I2Adas9XRVaEk8PRAI."">
            <id>http://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/base/16adsadsdasaa90ce88927</id>
            <updated>2015-08-10T16:49:22.280Z</updated>
            <app:edited
                xmlns:app="http://www.w3.org/2007/app">2015-08-10T16:49:22.280Z
            
            
            </app:edited>
            <category scheme="http://schemas.google.com/g/2005#kind" term="http://schemas.google.com/contact/2008#contact"></category>
            <title>Bhise</title>
            <link rel="http://schemas.google.com/contacts/2008/rel#photo" type="image/*" href="https://www.google.com/m8/feeds/photos/media/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/16aaa90ce88927"></link>
            <link rel="self" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin/16aaa90ce88927"></link>
            <link rel="edit" type="application/atom+xml" href="https://www.google.com/m8/feeds/contacts/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/thin/16aaa90ce88927"></link>
            <gd:name>
                <gd:fullName>Bhise</gd:fullName>
                <gd:givenName>Bhise</gd:givenName>
            </gd:name>
            <gd:organization rel="http://schemas.google.com/g/2005#work">
                <gd:orgName>Ref:kedar</gd:orgName>
            </gd:organization>
            <gd:email rel="http://schemas.google.com/g/2005#other" address="lnpxdasfas9511@gmail.com" primary="true"></gd:email>
            <gd:phoneNumber rel="http://schemas.google.com/g/20das05#mobile" uri="tel:+91-9922dsd9-26631">+91 99-22-926631</gd:phoneNumber>
            <gContact:groupMembershipInfo deleted="false" href="http://www.google.com/m8/feeds/groups/cdsadsdsoolndasdsdidsadtmadasns%40gmail.com/base/6"></gContact:groupMembershipInfo>
        </entry>
    </feed>

GoogleContactsDeserializable File

    struct GoogleContacts: XMLIndexerDeserializable {
        let fullName: String
        let email: String
    
        static func deserialize(_ node: XMLIndexer) throws -> GoogleContacts {
            return try GoogleContacts(
                fullName: node["gd:name"]["gd:fullName"].value(),
                email: node["gd:email"].value(ofAttribute: "address")
            )
        }
    }

ViewController

    let xml = SWXMLHash.parse(data)
    do {
        let nodes: [GoogleContacts] = try xml["feed"]["entry"].value()
        print(nodes)
    } catch let error {
        print(error)
    }

**Comment by drmohundro** [comment]
Looks like the XML parsing thinks the XML is invalid... just checking some of it, but the first line of the XML looks like it has some invalid termination of the string quote character... see:

```xml
<feed gd:etag="W/"DEENSH0_fit7I2A9XR9QEk8.""
    xmlns:openSearch="http://a9.com/-/spec/opensearch/1.1/"
```

The `gd:etag` attribute doesn't have the quotes correct. To escape the slash in the etag, it would need to be `\` instead of `/`. I don't know if there are other mismatched quotes or not, but I'd suggest simplifying the XML until you can get a match. That should help you see where the invalid XML is.

I'll often do a sanity check like this:

```swift
// doesn't work
var data = "<feed gd:etag=\"W/\"DEENSH0_fit7I2A9XR9QEk8.\"\"" +
"    xmlns:openSearch=\"http://a9.com/-/spec/opensearch/1.1/\"" +
"    xmlns=\"http://www.w3.org/2005/Atom\"" +
"    xmlns:gContact=\"http://schemas.google.com/contact/2008\"" +
"    xmlns:batch=\"http://schemas.google.com/gdata/batch\"" +
"    xmlns:gd=\"http://schemas.google.com/g/2005\">" +
"</feed>"

// works, removed the invalid gd:etag attribute
data = "<feed" +
"    xmlns:openSearch=\"http://a9.com/-/spec/opensearch/1.1/\"" +
"    xmlns=\"http://www.w3.org/2005/Atom\"" +
"    xmlns:gContact=\"http://schemas.google.com/contact/2008\"" +
"    xmlns:batch=\"http://schemas.google.com/gdata/batch\"" +
"    xmlns:gd=\"http://schemas.google.com/g/2005\">" +
"</feed>"

let xml = SWXMLHash.parse(data)

// ignore deserialization, if SWXMLHash can't even parse the root element, nothing will work
xml["feed"].all.count
```

**Comment by n1tesh** [comment]
xml["feed"].all.count works for me. (1 count)
 Also xml["feed"]["entry"] works.

I cannot change the data as it's what I get when I fetch Contacts from Google.

**Comment by drmohundro** [comment]
Maybe there is something going on with the data as it was posted in GitHub. Here are some things to check:

How many entries do you get back from `xml["feed"]["entry"].all.count`?

If one, then does anything return from the following?

```swift
xml["feed"]["entry"]["gd:name"]["gd:fullName"].all.count
```

**Comment by n1tesh** [comment]
@drmohundro 

xml["feed"].all.count =1
xml["feed"]["entry"].all.count = 4797
xml["feed"]["entry"]["gd:name"].all.count = 0
xml["feed"]["entry"]["gd:name"]["gd:fullName"].all.count = 0

`    func parseData(data: Data){
        let xml = SWXMLHash.parse(data)
        print(xml["feed"].all.count)
        print(xml["feed"]["entry"].all.count)
        print(xml["feed"]["entry"]["gd:name"].all.count)
        print(xml["feed"]["entry"]["gd:name"]["gd:fullName"].all.count)
        do {
            let nodes: [GoogleContacts] = try xml["feed"].value()
            print(nodes)

        } catch let error {
            print(error)
        }

    }`

**Comment by drmohundro** [comment]
Okay, this tells me that the XML parsing is finding multiple entries under feed / entry. Can you try:

```swift
xml["feed"]["entry"][0]["gd:name"].all.count
```

We know we're able to get down into the entry, so ideally, if we choose an individual entry, then we should be able to pull names off.

Then, from the first one, we could try:

```swift
xml["feed"]["entry"][0]["gd:name"]["gd:fullName"].value()
xml["feed"]["entry"][0]["gd:email"].value(ofAttribute: "address")
```

**Comment by n1tesh** [comment]
@drmohundro 

`
(lldb) po xml["feed"]["entry"][0]["gd:email"]
▿ 
  ▿ XMLError : XML Element Error: Incorrect key ["gd:email"]
    - Key : "gd:email"


(lldb) po xml["feed"]["entry"][0]["gd:name"]
▿ <gd:name><gd:fullName>Prashant Y AHY T</gd:fullName><gd:givenName>Prashant Y</gd:givenName><gd:additionalName>AHY</gd:additionalName><gd:familyName>T</gd:familyName></gd:name>
  ▿ Element : <gd:name><gd:fullName>Prashant Y AHY T</gd:fullName><gd:givenName>Prashant Y</gd:givenName><gd:additionalName>AHY</gd:additionalName><gd:familyName>T</gd:familyName></gd:name>


(lldb) po xml["feed"]["entry"][0]["gd:name"]["gd:fullName"]
▿ <gd:fullName>Prashant Y AHY T</gd:fullName>
  ▿ Element : <gd:fullName>Prashant Yadav AHY Tech</gd:fullName>
```

**Comment by drmohundro** [comment]
The fact that pulling `gd:email` isn't working makes me think that's part of the problem... if you change your deserializer to not pull the email (like below), does it return data?

```swift
struct GoogleContacts: XMLIndexerDeserializable {
    let fullName: String
    // let email: String

    static func deserialize(_ node: XMLIndexer) throws -> GoogleContacts {
        return try GoogleContacts(
            fullName: node["gd:name"]["gd:fullName"].value()
            // email: node["gd:email"].value(ofAttribute: "address")
        )
    }
}
```

That will at least narrow down for sure that it is the email that is causing the problem.

Then you might could try:

```swift
po xml["feed"]["entry"][0].description
```

**Comment by n1tesh** [comment]
@drmohundro 

**po xml["feed"]["entry"][0].description**
`<entry gd:etag=\"\"QHc_fTVSLSt7I2A9XR9SEkUDTgM.\"\"><id>http://www.google.com/m8/feeds/contacts/nitesh.I%40companyinc.com/base/30bc4520a0c9a57</id><updated>2017-04-04T07:12:51.945Z</updated><app:edited xmlns:app=\"http://www.w3.org/2007/app\">2017-04-04T07:12:51.945Z</app:edited><category scheme=\"http://schemas.google.com/g/2005#kind\" term=\"http://schemas.google.com/contact/2008#contact\"></category><title>Nothu Vishwakarma</title><link rel=\"http://schemas.google.com/contacts/2008/rel#photo\" type=\"image/*\" href=\"https://www.google.com/m8/feeds/photos/media/nitesh.I%40companyinc.com/30bc4520a0c9a57\"></link><link rel=\"self\" type=\"application/atom+xml\" href=\"https://www.google.com/m8/feeds/contacts/nitesh.I%40companyinc.com/thin/30bc4520a0c9a57\"></link><link rel=\"edit\" type=\"application/atom+xml\" href=\"https://www.google.com/m8/feeds/contacts/nitesh.I%40companyinc.com/thin/30bc4520a0c9a57\"></link><gd:name><gd:fullName>Nothu Vishwakarma</gd:fullName><gd:givenName>Nothu</gd:givenName><gd:familyName>Vishwakarma</gd:familyName></gd:name><gd:email rel=\"http://schemas.google.com/g/2005#other\" address=\"Nothu.vishwakarma@companyinc.com\" primary=\"true\"></gd:email></entry>`

Change deserializer to pull only name didnt help. Same error `This node is invalid`

**Comment by drmohundro** [comment]
Do you have a simple code example that reproduces the issue that you could upload somewhere? Just seeing the data here, it looks like things should work, especially given that it seems like calls like `xml["feed"]["entry"][0]` works. If that works, it means that SWXMLHash is populating its internal data structure and has already parsed.

**Comment by n1tesh** [comment]
@drmohundro 

https://github.com/kalvish21/google-contacts-swift3 - This is w/o using SWXMLHash

**Comment by n1tesh** [comment]
@drmohundro 

https://github.com/n1tesh/GoogleContacts Use this. Just signin and try.

Thanks.

**Comment by n1tesh** [comment]
Hi @drmohundro , Have you checked the above example ?

**Comment by drmohundro** [comment]
FYI, I started looking at this - first off, just a note, but the XML content coming back is in a somewhat different format than I expected. For example, there can be multiple `gd:email` tags coming back if the Google contact has multiple emails, or one. Same thing with phones. SWXMLHash is parsing it correctly, but the indexing can be different.

See below for my debugging and how there are 3 elements coming back for email:

```
(lldb) po xml["feed"]["entry"][0]["gd:name"].description
"<gd:name><gd:fullName>David Mohundro</gd:fullName><gd:givenName>David</gd:givenName><gd:familyName>Mohundro</gd:familyName></gd:name>"


(lldb) po xml["feed"]["entry"][0]["gd:email"].all.count
3


(lldb) po xml["feed"]["entry"][0]["gd:email"][0].description
"<gd:email rel=\"http://schemas.google.com/g/2005#home\" address=\"david@mohundro.com\" primary=\"true\"></gd:email>"


(lldb) 
```

Your GoogleContacts struct will need to handle multiple emails I think.

Hope this at least gives you a little more direction.

**Comment by n1tesh** [comment]
@drmohundro even If I try it with name only still it throws `This node is invalid:`. Have you tried creating struct file/Deserializing response ?

**Comment by drmohundro** [comment]
It looks like some of the contacts coming back don't have names... see my tweak to your `GoogleContacts` struct:

```swift
struct GoogleContacts: XMLIndexerDeserializable {
    let fullName: String
    let email: String
    
    static func deserialize(_ node: XMLIndexer) throws -> GoogleContacts {
        if node["gd:name"].element != nil {
            return try GoogleContacts(
                fullName: node["gd:name"]["gd:fullName"].value(),
                email: "test"
                //email: node["gd:email"].value(ofAttribute: "address")
            )
        }
        else {
            return GoogleContacts(
                fullName: "no name for this contact",
                email: "test"
            )
        }
    }
}
```

There is an `entry` element coming back, but it doesn't have all of the fields.

**Comment by n1tesh** [comment]
@drmohundro It always `[Quorg.GoogleContacts(fullName: "no name for this contact", email: "test")]`
Have you tried it ?

**Comment by drmohundro** [comment]
Oh, one other change that I had to make... change to:

```swift
```

**Comment by n1tesh** [comment]
Thanks it works if there exists single email address.

**Comment by drmohundro** [comment]
Right - I think you'll probably need to modify `GoogleContacts` so that `email` is a string array. I *think* it will work without any other modifications then.
