### ISSUE TITLE
Compile error - CLI Project

### ISSUE THREAD

**Issue by Teeds** [drmohundro/SWXMLHash#13]
Initial Cococapod install worked and I was able to play around in playground.

I then went to implement the code outside of the playground by adding "import SWXMLHash". I know get the following compile error 

    "<unknown>:0: error: could not build Objective-C module 'SWXMLHash'" 

which isn't very helpful

My playground also stopped working with the following error

    "Playground execution failed: could not build Objective-C module 'SWXMLHash'A fatal parse error has occurred.  LLDB may become unstable; please restart your debug session as soon as possible."

I suspect it is an Xcode build / config problem or pod build problem since it initial worked in the playground.

I tried replicating the initial setup that worked with the playground, but haven't been able to.

I am lost at how to track the issue down? Any tips, tricks or suggestions?

**Comment by tkrajacic** [comment]
Some more information would be helpful:
So, you have an Xcode project and include SWXMLHash as cocoapod?
You are using the workspace that was created for you by cocoapods?
What does `pod --version` give you on the command line?
The playground is part of a project/workspace?
Where was the playground when you initially tried your code? Was it the playground that came with the SWXMLHash repo?

**Comment by drmohundro** [comment]
I think there may still be issues with my build configuration *specifically* when targeting OSX as opposed to iOS. I've been trying off and on to tweak the Build Settings for both targets so that the same Swift code works for both, but I think something may be off. I'm curious if there may be something there.

I will say that I'm fairly confident that the actual source code is fine, I just think I missed some config setting somewhere.

Of course, that may have nothing to do with this either.

**Comment by Teeds** [comment]
@tkrajacic below is the processed I went through to start (generate) the project.

1.Created a new OS X > Application > Command Line Tool
2.Added a Podfile
    source 'https://github.com/CocoaPods/S...
    platform :osx, '10.10'
    pod 'SWXMLHash', '~> 0.6.0'

3.Goto terminal and "pod install"
4.Reopen project in new workspace generated by CococaPods
5.Add import SWXMLHash to generated swift project
6.Press build
7.Compile error

After the last update it worked for a time while messing around in the Playgrounds

Given it is a compile error and that there is nothing popping up in the IDE it makes me think it is a build setting. The compile error is also being flagged by Xcode during compile in every swift file (including other library files). Even if there is no import of SWXMLHash to that file. Making me thinking it is linking back to the Pod build or something in the Pod build settings causing the error.

I'm new to Xcode (and Xcode build process), so not sure the best way to work the issue so was looking for some advice on the best way to fault find this one? Happy to do the playing around.

**Comment by tkrajacic** [comment]
Well for starters, it is impossible to use frameworks in Swift command line tools.
Since you are using Cocoapods, that is what gets built for Swift pods.
Not sure how this ever could have worked in a CLI target, because it couldn't have ;)

**Comment by drmohundro** [comment]
@tkrajacic that helps a lot, I didn't know command line tools didn't support frameworks. Also, I had been considering breaking the source file out into separate files, but knowing that there are cases where CocoaPods or another package manager won't currently work for all scenarios, I'll just keep everything in one file for now.

@Teeds does this help answer your question? If you clone the source and just drop SWXMLHash.swift into your code directly, does everything work as expected then?

**Comment by Teeds** [comment]
@drmohundro If I copy the source into the project SWXMLHash works as expected.

Bummer about frameworks support for CLI Swift projects.

Thanks @tkrajacic
