### ISSUE TITLE
The naming of 'Element' from SWXMLHash.XMLIndexer causes a build failure in Xcode 9

### ISSUE THREAD

**Issue by jacquelinelee** [drmohundro/SWXMLHash#140]
I found a related issue on the apple swift bugs site: https://bugs.swift.org/browse/SR-4951

When I attempt to build with SWXMLHash on Xcode 9, I encounter the following error:
SWXMLHash.XMLIndexer:72:22: error: invalid redeclaration of 'Element'
    public typealias Element = (SWXMLHash.XMLIndexer)

I can rename 'Element' (at line 457 of SWXMLHash.swift) to 'element' using Xcode9's new rename feature and my build works.

**Comment by drmohundro** [comment]
Have you checked out the latest version `4.0.0`? Via #133? That should have introduced the rename from `Element` to `element` along with other enum renames which should have resolved this.

**Comment by skofgar** [comment]
Thanks @drmohundro – using 4.0.0 resolved the problem for me

**Comment by codeslubber** [comment]
The code compiles now, but the implementation of the Sequence Protocol was dropped from XMLIndexer, which is causing issues in our code?

**Comment by drmohundro** [comment]
Is your current usage `for val in xml["elem"]`?

If so, just add `.all` at the end - it does the same as the prior approach did.

**Comment by codeslubber** [comment]
Yah we figured it out, thanks.

**Comment by drmohundro** [comment]
Closing this as I think this should be resolved.

**Comment by tobujin** [comment]
The code compiles now, but the implementation of the Sequence Protocol was dropped from XMLIndexer.Error occurs  " Value of type 'XMLIndexer' has no member 'flatMap' ".how to use flatMap .

**Comment by tobujin** [comment]
I have download the wendercast Sample from the raywenderlich.com.
but I could not the wendercast project .Error same as the above.so I changed the SWXMLHash.swift file as you mentioned. the other error occurs. 
" value of type 'XMLIndexer' has no member 'flatMap' ".
flatMap was the Sequence's function. How to implement flatMap? @drmohundro
