### ISSUE TITLE
xml validation

### ISSUE THREAD

**Issue by davibe** [drmohundro/SWXMLHash#141]
it seems to me that swxmlhash can load partial documents if the document has a parse error in the middle of it. What's the simplest way to perform validation and fail if there is an error ?

**Comment by drmohundro** [comment]
That looks like some missing functionality at the moment, though it looks like the underlying `Foundation.XMLParser` provides a `parserError` value that can be checked. This is definitely something that would be beneficial to the library, though it probably makes sense to have the public API throw an error.

**Comment by Isuru-Nanayakkara** [comment]
+1 A way to throw an error if the XML parsing fails for any reason would be a good addition.

**Comment by drmohundro** [comment]
@davibe @Isuru-Nanayakkara - I just pushed #169 as an initial attempt to add something for this. I'd welcome your thoughts on the approach. To avoid a breaking change in the API (as well as prior usage), it is enabled via a config setting and is enum-based versus throwing an error.

The error does return the column and line number for where the parser detected the problem.

Let me know what you think!

**Comment by drmohundro** [comment]
I didn't hear anything back, so I'm assuming what I've got will work well enough - I just pushed out `4.6.0` with this feature. Thanks again for the suggestion!
