### ISSUE TITLE
No such module 'SWXMLHash' on xCode 8.3.3

### ISSUE THREAD

**Issue by pepper28** [drmohundro/SWXMLHash#143]
I'm having trouble adding SWXMLHash to my project under xCode 8.3.3.  I have followed the installation procedures exactly except I can not have the deployment target downgraded to 8.0 I need it at 9 and above or other things fail.  Can you direct me how to address this issue.

**Comment by drmohundro** [comment]
Which installation procedures are you using? Carthage? CocoaPods? Manual? If one of those, then can you also share the contents of your `Podfile` or `Cartfile` please?

**Comment by pepper28** [comment]
CocaPods

# Uncomment this line to define a global platform for your project

platform :ios, '10.0'
source 'https://github.com/CocoaPods/Specs.git'
target 'MyApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!
  # Pods for AWS Cognito User Pool

      pod 'AWSCognitoIdentityProvider'
      pod 'AFNetworking'
      pod 'SwiftCircularIconButtonWithProgressBar'
      pod 'SwiftyJSON', '3'
      pod 'Alamofire', '~> 4.4'
      pod 'HanekeSwift', :git => 'https://github.com/Haneke/HanekeSwift.git', :branch => 'feature/swift-3'
      pod 'AWSCloudWatch'
      pod 'AWSCognito'   
      pod 'AWSEC2'
      pod 'AWSElasticLoadBalancing'
      pod 'AWSMobileAnalytics'
      pod 'AWSS3'
      pod 'AWSSES'
      pod 'AWSSimpleDB'
      pod 'AWSSNS'
      pod 'AWSSQS'
      pod 'Google/SignIn'
      pod 'PopupDialog', '~> 0.5'
      pod 'SwiftRangeSlider'
      pod 'SWXMLHash', '~> 4.0.0'   
end

**Comment by pepper28** [comment]
I was able to discern what was causing my issue.  I had previously renamed my cocoapods project before I ever loaded the SWXMLHash pods.  This caused the problem becuase it was targeting the prior project name.

**Comment by drmohundro** [comment]
Ahh, gotcha. Glad you got it figured out and thanks for updating the issue! Hope things are well.
