### ISSUE TITLE
Compile fail in XCode 9 b6 - 'Element' previously declared here (Fix attached)

### ISSUE THREAD

**Issue by kebl0155** [drmohundro/SWXMLHash#147]
Hi there,

We're using SWXMLHash in an app that serves over a million people, and I'm a bit worried it might stop working once iOS 11 comes out.

To test, I've downloaded and installed XCode 9.0 Beta 6.  I've duplicated the entire XCode workspace, also done a pod update, and rebuilt the .xcworkspace.

Unfortunately, no matter what I do the app will no longer compile.  XCode replies with a Swift Compiler Error, saying "Invalid redeclaration of 'Element' : 'Element' previously declared here."

When I click on the error, SWXMLHash.swift is opened and a number of instances of the word 'Element' are highlighted.

I am not sure if I am good enough at Swift to fix this, but I was able to get it all to compile by decapitalising the cases throughout (so .Element becomes .element, .List becomes .list and so on) with Find and Replace.

I don't know if this has changed its operation in any substantive way, so I thought it best to raise this as an issue.

[SWXMLHashFix.zip](https://github.com/drmohundro/SWXMLHash/files/1245846/SWXMLHashFix.zip)

I have attached my modified source code; perhaps you might consider taking a look 
and adding them to the source tree?  I hereby disclaim any copyright or other ownership of these modifications, in case you need that.

**Comment by drmohundro** [comment]
@kebl0155 which version of SWXMLHash are you using?

This was fixed as of version 4.0.0. If you're using CocoaPods or Carthage, you should be able to just change to target 4.0.0 instead. So, for CocoaPods, change your `Podfile` to have `pod 'SWXMLHash', '~> 4.0.0'` instead. Or with Carthage, it will say `github "drmohundro/SWXMLHash" ~> 4.0`.

**Comment by kebl0155** [comment]
Ah it was my understanding of pod that was at fault then.  Thank you for the clarification and sorry to have troubled you.

**Comment by drmohundro** [comment]
No worries, I'm happy to help! I'll go ahead and close this issue, but feel free to re-open if necessary.
