### ISSUE TITLE
XML parsing as pagination

### ISSUE THREAD

**Issue by santhoshs5** [drmohundro/SWXMLHash#150]
I have an XML file which i get downloaded from server which is having 50k elements. I need to display those 50k elements in a tableView. But It consumes more memory.

Can I achieve this using this framework.

**Comment by drmohundro** [comment]
The closest thing that the framework currently has is the lazy parsing. See:

```swift
let xml = SWXMLHash.config {
              config in
              config.shouldProcessLazily = true
          }.parse(xmlToParse)
```

Lazy parsing means that only the parts of the XML that you query are loaded into memory. I think it could work in your case, even though it does sound like you want everything ultimately parsed. It uses the indexes specified to determine how much of the XML to load into memory. So I think you'd have to re-parse it each time you want a new page.

Hope this helps - let me know if I can clarify.

**Comment by drmohundro** [comment]
Hi, I'm closing this ticket as I haven't heard back in a few months... feel free to comment back if you still have questions. Thanks!
