### ISSUE TITLE
SWXMLHash cocoapod is not Swift 4 compatible

### ISSUE THREAD

**Issue by 0xMarK** [drmohundro/SWXMLHash#151]
Please upgrade the code base to Swift 4.

**Comment by drmohundro** [comment]
@0xMarK which version are you using? If you change your `Podfile` to have `pod 'SWXMLHash', '~> 4.0.0'` in it, it should be fine.

**Comment by 0xMarK** [comment]
@drmohundro Hi! We were using v4.1.1 and then installed Xcode 9. I've pressed the "Conversion to Swift 4 is available" to upgrade the project to Swift 4. After that Xcode proposes to upgrade the pod SWXMLHash to Swift 4 language. Even if I update the pod to v4.2.1 I still get the proposal to upgrade the pod.
Can you help me with that? I suppose you could just release the update, because you've already done some changes for Xcode 9 compatibility.
Thanks in advance!

**Comment by drmohundro** [comment]
Oh, I see - sorry for the confusion. I'm trying to get the Travis build happy first, but then I can push a minor fix out.

**Comment by 0xMarK** [comment]
BTW automatic Swift 4 migrator does not propose any changes to SWXMLHash's code...

**Comment by drmohundro** [comment]
Right, it was simply project changes - the code should work as is.

**Comment by drmohundro** [comment]
I just pushed `4.2.2` - can you see if that resolves the issues for you? It has no Xcode 9-related warnings for me anymore.

**Comment by 0xMarK** [comment]
Thanks a lot @drmohundro! It worked. Though migration to Swift 4 is tough when you have a lot of targets and a lot of pods.
