### ISSUE TITLE
No such module 'SWXMLHash'

### ISSUE THREAD

**Issue by katbaguisi** [drmohundro/SWXMLHash#157]
I am having problems adding SWXMLHash to my project. I installed it manually and whenever I import it to a swift file in my project, it shows the error: "No such module 'SWXMLHash'". I'm using Xcode 8.3.3 and my deployment target is 8.0

**Comment by drmohundro** [comment]
For manual installation, did you just include the `SWXMLHash.swift` file in your own project? If not, could you tell me what you did to install it manually?

**Comment by katbaguisi** [comment]
I cloned the SWXMLHash repository and added the file SWXMLHash.swift to my project.

**Comment by drmohundro** [comment]
I just noticed something - if you just add the file to project, you won't need to put an `import SWXMLHash` line in your code. You can just being using SWXMLHash directly as it isn't a separate module if you drop it in your project.

**Comment by katbaguisi** [comment]
Thanks a lot! It works now 👍
