### ISSUE TITLE
'characters' is deprecated: Please use String or Substring directly

### ISSUE THREAD

**Issue by bracketslash** [drmohundro/SWXMLHash#163]
Line 419 of SWXMLHash+TypeConversion.swift should be replaced with
if !textVal.isEmpty {

**Comment by drmohundro** [comment]
Done! Let me know if you need a point release tagged for this, too.

**Comment by jpsim** [comment]
I'd appreciate a release tag for this 🙏

**Comment by drmohundro** [comment]
👍 just pushed 4.2.4

**Comment by jpsim** [comment]
Thanks!
