### ISSUE TITLE
CDATA isn't parsed in Linux?

### ISSUE THREAD

**Issue by agordeev** [drmohundro/SWXMLHash#172]
Looks like the library can't work under Ubuntu 14.04 and Swift 4.0.3? `XMLElement.text` value is empty. Probably related to `XMLParserDelegate`

**Comment by drmohundro** [comment]
Can you provide the following?

* Swift version being used - `swift --version`
* Sample XML being used?
* Repro steps?

It should work on Ubuntu just fine - I ran the test suite on Ubuntu 16.04 just a week or two ago and Travis verifies it, too.

Something else you could try is cloning the repo and running:

```
swift build
swift test
```

Hope we can figure out what is going on!

**Comment by drmohundro** [comment]
Sorry just noted that you said Swift 4.0.3. Would you mind cloning the repo to see if any tests fail?

**Comment by agordeev** [comment]
Thanks for the quick answer. So all the tests pass just fine with the default `test.xml`.

However, if I replace it by [this xml](https://www.upwork.com/ab/feed/jobs/rss?subcategory2=game_development) there are two failures:

`WhiteSpaceParsingTests.testShouldBeAbleToPullTextBetweenElementsWithoutWhitespace`
`LazyWhiteSpaceParsingTests.testShouldBeAbleToPullTextBetweenElementsWithoutWhitespace`

**Comment by agordeev** [comment]
I prepared a test project: https://github.com/agordeev/SWXMLHash.git

I removed all your tests and added a new one with sample XML I'm using. If you run tests on your Mac, they run just fine. However, when I clone it to my Ubuntu 14.04 server they fail:

```
$ /home/andreygordeev/.swiftenv/versions/4.0.3-RELEASE/usr/bin/swift test
Compile Swift Module 'SWXMLHash' (2 sources)
Compile Swift Module 'SWXMLHashTests' (2 sources)
Compile Swift Module 'SWXMLHashPackageTests' (1 sources)
Linking ./.build/x86_64-unknown-linux/debug/SWXMLHashPackageTests.xctest
Test Suite 'All tests' started at 2018-01-16 06:55:49.559
Test Suite 'debug.xctest' started at 2018-01-16 06:55:49.587
Test Suite 'XMLParsingTests' started at 2018-01-16 06:55:49.587
Test Case 'XMLParsingTests.test1' started at 2018-01-16 06:55:49.588

/home/andreygordeev/SWXMLHash/Tests/SWXMLHashTests/XMLParsingTests.swift:325: error: XMLParsingTests.test1 : XCTAssertTrue failed - 
Test Case 'XMLParsingTests.test1' failed (0.01 seconds)
Test Suite 'XMLParsingTests' failed at 2018-01-16 06:55:49.601
	 Executed 1 test, with 1 failure (0 unexpected) in 0.01 (0.01) seconds
Test Suite 'debug.xctest' failed at 2018-01-16 06:55:49.602
	 Executed 1 test, with 1 failure (0 unexpected) in 0.01 (0.01) seconds
Test Suite 'All tests' failed at 2018-01-16 06:55:49.602
	 Executed 1 test, with 1 failure (0 unexpected) in 0.01 (0.01) seconds
```

As you can see, `print(titleField!.text)` prints empty string on Ubuntu.

**Comment by agordeev** [comment]
Can you please try to run it on your server and let me know results? May be it's just Ubuntu 14.04 issue

**Comment by drmohundro** [comment]
This is great, thanks - I appreciate the repro steps. I'll see if I can figure out what is going on.

**Comment by agordeev** [comment]
Thank you very much @drmohundro for such quick response!

**Comment by drmohundro** [comment]
Good news - I figured out what the difference was and I've got a pull request in place. It does appear that the `XMLParser` implementation on Linux versus Mac is slightly different, but it is easy to work around. Once the build passes, I'll see about getting a version fix pushed out.

**Comment by agordeev** [comment]
@drmohundro works great, you're the best! Thank you very much! 👍
