### ISSUE TITLE
Fetching from inside element

### ISSUE THREAD

**Issue by ankitbisht143** [drmohundro/SWXMLHash#176]
<PrintLetterBarcodeData state="Tamil Nadu" name="Sangeetha D" dist="Tiruvallur" dob="03/06/1989"></PrintLetterBarcodeData>

this is my data.. How to fetch a particular value like name from this..

**Comment by drmohundro** [comment]
I'm not seeing any data... could you look at your comment again and see if there a formatting issue or something?

**Comment by ankitbisht143** [comment]
@drmohundro 
<PrintLetterBarcodeData state="Delhi" name="Mangal Singh" dob="02/03/1963"></PrintLetterBarcodeData>

This is my data

**Comment by ankitbisht143** [comment]
@drmohundro 
`<PrintLetterBarcodeData state="Delhi" name="Mangal Singh" dob="02/03/1963"></PrintLetterBarcodeData>`
This is my data

**Comment by drmohundro** [comment]
Are you asking how to pull the name attribute from your XML? That's documented at https://github.com/drmohundro/SWXMLHash#attributes-usage.

So, assuming you've already got that value, it'd be like this:

```swift
xml["PrintLetterBarCodeData"].element!.attribute(by: "name")!.text
```

**Comment by drmohundro** [comment]
I'm going to go ahead and close this as there hasn't been any activity - feel free to comment and re-open if you still are having issues. Thanks!
