### ISSUE TITLE
CDATA Escaped characters

### ISSUE THREAD

**Issue by ggyggy** [drmohundro/SWXMLHash#180]
**Issue:** 
Special characters like `&`, `"`, `<`, `>`, `'` that can appear in a CDATA section are not replaced by their associated escaped string. This cause a problem when trying to parse a string which comes from an XMLIndexer description method.

**Steps to reproduce:**

    let xmlIndexer = SWXMLHash.parse("<some xml>")
    let description = xmlIndexer.description  
    let xmlIndexer2 = SWXMLHash.parse(description)     

=> `xmlIndexer2` has some missing nodes and inconsistent state because of the unescaped characters like `&` contained in `description` variable.

**Possible solution:**
Replace special characters by their associated escaped string in `func parser(_ parser: XMLParser, foundCDATA CDATABlock: Data)` method.

**Comment by drmohundro** [comment]
The `description` property doesn't actually return inner content, instead it returns the textual representation of the entire XML element currently indexed. See below from the tests:

```swift
    func testShouldBeAbleToProvideADescriptionForTheDocument() {
        let descriptionXml = "<root><foo><what id=\"myId\">puppies</what></foo></root>"
        let parsed = SWXMLHash.parse(descriptionXml)

        XCTAssertEqual(parsed.description, "<root><foo><what id=\"myId\">puppies</what></foo></root>")
    }
```

To get the textual content of an element with CDATA in it, you'd instead use the `text` property off of the element. Like so:

```swift
xml!["some"]["elem-with-cdata"].element?.text
```

Does this help?

**Comment by drmohundro** [comment]
I'm going to go ahead and close this as there hasn't been any activity - feel free to comment and re-open if you still are having issues. Thanks!
