### ISSUE TITLE
Accessing part of XML string

### ISSUE THREAD

**Issue by cmcgheit** [drmohundro/SWXMLHash#183]
Great Library!

I looked through some other issues, but I didn't see anything involving my question. I would like to know if I can access a certain part of the XML string of data? So, let's say for example I have the following XML data:

```
<root>
   <catalog>
    <book>
    <title>Book</title>
    <description>This is the book description. This book has 100 pages</description>
    </book>
    <book>
    <title>Book 2</title>
    <description>This is the book 2 description. This book has 500 pages</description>
    </book>
    <book>
    <title>Book 3</title>
    <description>This is the book 3 description. This book has 250 pages</description>
    </book>
  </catalog>
</root>
```

I know I can access the description tag with:
`xml["root"]["catalog"]["book"]["description"].element?.text`

But, if I wanted to organize the data by the number of pages, how would I access just the "This book has x number of pages" part of string? Would I use XMLAttributeDeserializable? XMLElementDeserializable?

I know there are some other Apple frameworks I can use for accessing strings, but I wanted to see if I could access this part of the XML tag with this library exclusively? 

Thanks!

**Comment by drmohundro** [comment]
When you say "organize the data", can you help me understand a little more about what you're trying to do? And you mentioned both `XMLAttributeDeserializable` and `XMLElementDeserializable` - are you doing custom deserialization into your own types?

SWXMLHash doesn't provide any functionality for pulling content out of the element text directly as it is just string content at that point. You could use the custom deserialization support and then add some custom string parsing when pulling the values out.

**Comment by cmcgheit** [comment]
I planned on organizing the data in categories, so like the example, organize them by the number of pages. I asked about XMLElementDeserializable/XMLAttributeDeserializable because in the date example, you pulled the date element from the XML string. I thought there maybe a way to do that to achieve what I am trying to achieve.

**Comment by drmohundro** [comment]
Ahhh, I see. Yes, you could implement `XMLElementDeserializable` in this case (because the `description` is an XML element). Then, in the `deserialize` method, you'd do your custom string parsing there. You'd probably want to deserialize it to a custom type instead of `string`, though, because the logic would fire for _any_ string coming back, and you'd only want it for the `description` element. Does that make sense?

**Comment by cmcgheit** [comment]
I think so. I'm already using XMLIndexerDeserializable to return the `title` and `description` tag as a whole:

```
struct Book {
var title: String
var desc: String

static func deserialize(_ node: XMLIndexer) throws -> Book {
        return try Book(
            title: node["title"].value(),
            desc: node["description"].value()
     )
   }
}
```
I have been experimenting with setting up a new struct for the categories of type `XMLElementDeserializable` and also seeing if I can achieve categories by using subindexer. Thanks for your help thus far!

**Comment by drmohundro** [comment]
Hey, just checking in - did you need any additional help here? If not, I'll go ahead and close this issue. Thanks!

**Comment by cmcgheit** [comment]
Thanks for checking. I just used the range on the string. I'll close the issue now.
