### ISSUE TITLE
How to use the filter element?

### ISSUE THREAD

**Issue by thejeraldo** [drmohundro/SWXMLHash#189]
I am trying to use the [filtering method](https://github.com/drmohundro/SWXMLHash#filtering-elements) however it doesn't seem like the method is there? It doesn't appear on autocomplete nor did I saw it in the source file in my Cocoapods project.

How do I filter from multiple elements having the same key and get one that has a specific value?

**Comment by drmohundro** [comment]
Sorry you're having trouble - you mentioned that you're using CocoaPods... which version of SWXMLHash are you targeting in your Podfile?

**Comment by drmohundro** [comment]
I'm going to go ahead and close this issue - if you're still having issues, though, please feel free to comment. Thanks!
