### ISSUE TITLE
Extract content of tag

### ISSUE THREAD

**Issue by JaapWijnen** [drmohundro/SWXMLHash#190]
More of a question than an issue. Is it possible to extract the xml text from a chosen xml tag? For example

`<root><item><ball></ball><square></square><triangle></triangle></item></root>`

the result I would want would be some function to be called on `xml["root"]["Item"].asText()`
which would return `<ball></ball><square></square><triangle></triangle>`

**Comment by drmohundro** [comment]
You should be able to use either the `description` or `innerXML` property to get that. One gives the description of the currently indexed element while the innerXML property gives you the descriptions of the child elements.

Hope this helps!

**Comment by JaapWijnen** [comment]
Awesome! thanks. Missed those properties!
