### ISSUE TITLE
Add "swift_version" to podspec

### ISSUE THREAD

**Issue by JettF** [drmohundro/SWXMLHash#196]
Going forward, pods that have converted to Swift 4.2 or later will be unable to push to the trunk if they depend on SWXMLHash. This is because Cocoapods now checks for <'swift_version' = 'x.x'> in the podspec for a pod, if it is missing, it sets the swift version to the version of the project importing SWXMLHash which could potentially cause build errors.

**Comment by drmohundro** [comment]
👍thanks for the report! Per the docs, looks like it just needs a `spec.swift_version = '4.2' line, correct?

**Comment by JettF** [comment]
Yep! Or '4.0' if you haven't converted yet. You can also delete the now outdated .swift_version file.

**Comment by drmohundro** [comment]
Thanks again for the report - I just pushed out `4.7.4`!
