### ISSUE TITLE
Add CocoaPods support.

### ISSUE THREAD

**Issue by drmohundro** [drmohundro/SWXMLHash#2]
Once CocoaPods is ready to go to support Swift, it should be added here.

**Comment by RobbieClarken** [comment]
The current beta release of CocoaPods [supports Swift frameworks](http://blog.cocoapods.org/Pod-Authors-Guide-to-CocoaPods-Frameworks/) and seems perfectly functional. It would be great to get SWXMLHash added.

**Comment by drmohundro** [comment]
Thanks for the heads up! I had seen the news of Swift support in the beta, but I hadn't had a chance to adding it. I just pushed a Podspec file up, but I'm having issues with code signing when I run `pod lint`.

In the meantime, you can still reference it directly using `pod 'SWXMLHash', :git =>  https://github.com/drmohundro/SWXMLHash.git` if you'd like to test it, though. I'll see if I can resolve the code signing + pod lint issue and get it pushed to pod trunk.

**Comment by drmohundro** [comment]
It sounds like the plan for `pod lib lint` is to not require code signing; however, in the meantime, I temporarily signed SWXMLHash so that it would lint successfully so that I could push it to trunk. You can see the commit at https://github.com/CocoaPods/Specs/commit/bb22a6bcb062bed51b68b7395e5d9d40af8530d5. Once all of the hooks fire, it should be public.

**Comment by drmohundro** [comment]
Looks like it is live - see http://cocoadocs.org/docsets/SWXMLHash/0.6.0/. Let me know if you run into any issues with it.

**Comment by RobbieClarken** [comment]
Works perfectly, thanks!
