### ISSUE TITLE
Lazy parser cannot evaluate any elements after first call to .element

### ISSUE THREAD

**Issue by TempixTL** [drmohundro/SWXMLHash#203]
Hey there! I'm using Xcode 10.1, targeting iOS 11.0 and I think I've found a bug in the lazy parser.
With the following code snippet
```
let xml = """
<root>
	<val1>John</val1>
	<val2>Fred</val2>
	<val3>Sam</val3>
</root>
"""

let parser = SWXMLHash.lazy(xml)
		
let elem1 = parser["root"]["val1"].element!
let elem2 = parser["root"]["val2"].element!
```
`elem1` is evaluated successfully, but I get an `Unexpectedly found nil while unwrapping an Optional value` error on the line beginning with `let elem2 =`. 
Additionally, Switching the order of assignment of `elem1` and `elem2` reveals that `.element` always returns nil the second time it's called. For example, if the last 2 lines in the example above are replaced with
```
let elem2 = parser["root"]["val2"].element!
let elem1 = parser["root"]["val1"].element!
```
`elem2` successfully evaluates and `elem1` is unexpectedly nil.

In my testing, if the force-unwraps (`!`) are omitted (so we can observe the resulting values) and more assignments are added, such as `let elem3 = xml["root"]["val3"].element`, the `.element` call will return nil every time after the first.
This logically extends too `.value()` as well, and `XMLDeserializationError.NodeIsInvalid` is thrown on every call to it after the first.

 If I instead use the regular parser with `SWXMLHash.parse(xml)` all the elements are successfully evaluated, so I believe this issue is unique to the lazy parser.

**Comment by drmohundro** [comment]
Thanks for the report! I can confirm this behavior as well - I'm looking into it at the moment.

**Comment by drmohundro** [comment]
@TempixTL well I was able to get a fix in place - see #204. It was related to some streaming state that wasn't being fully reset. I'll see about getting this merged and a fix pushed out shortly.

**Comment by drmohundro** [comment]
@TempixTL FYI, I just pushed out `4.7.6` that includes the fix. Thanks again for the bug report!

**Comment by TempixTL** [comment]
No problem, thank you for the quick fix!
