### ISSUE TITLE
Question: Is it possible to use SWXML with Objective-C?

### ISSUE THREAD

**Issue by howardvining** [drmohundro/SWXMLHash#208]
Hi,
Does the latest version of SWXMLHash support Objective-C? It seems the SWXMLHash-Swift.h header file only exposes the FullXMLParser and LazyXMLParser but not the convenience parse functions.

Thanks

**Comment by drmohundro** [comment]
Hi @howardvining - great question and I honestly am not sure. I suspect it should, but I haven't used it in an ObjC project before and the earliest usage with iOS required the SWXMLHash-Swift.h file. I suspect that it should, though.

**Comment by drmohundro** [comment]
Just checking back on this question - were you able to make any forward progress here?

**Comment by mp2526** [comment]
Just to answer this...It appears to be working in my Objective C app. You have to  jump through some hoops because structs aren't supported in Objective C. I haven't fully tested yet, but I essentially created some classes and then extended them like your NSDate example.

**Comment by drmohundro** [comment]
That's great to hear, thanks for checking on that @mp2526!
