### ISSUE TITLE
swift version issue

### ISSUE THREAD

**Issue by wangwentong-lunaon** [drmohundro/SWXMLHash#211]
SWIFT_VERSION = 3.0 bug xcode of 10.2 is not Compatible

**Comment by drmohundro** [comment]
Thanks for the report - already a pull request in progress to address this, should be merged shortly, see #210

**Comment by drmohundro** [comment]
Hi @wangwentong-lunaon - I just pushed out `4.9.0` to fully support Swift 5.0 and Xcode 10.2. That should resolve this, but let me know if you still see issues.
