### ISSUE TITLE
Support for armv7

### ISSUE THREAD

**Issue by smahurkar** [drmohundro/SWXMLHash#214]
I am getting the following error when I try to build or archive using Xcode:

Could not find module 'SWXMLHash' for architecture 'armv7'; found: arm64

**Comment by drmohundro** [comment]
Which version of Xcode are you using? Also, are you using CocoaPods, Carthage, or something else to use the library?

**Comment by smahurkar** [comment]
Version 10.2.1 (10E1001)
CocoaPods
This issue occurs with: platform :ios, '12.0', but not with platform :ios, '11.0'

**Comment by drmohundro** [comment]
I'm not positive, but I think it had to with the combination of iOS 12 and Xcode 10... check out the comments on this SO post - https://stackoverflow.com/a/55994693. That entire thread seems related to this as well. Maybe this helps?

**Comment by drmohundro** [comment]
FYI, I’m going to close this for now as there hasn’t been activity in a few months - if you’re still having issues, please let me know.
