### ISSUE TITLE
Ambiguous use of 'Element'

### ISSUE THREAD

**Issue by rahul-apple** [drmohundro/SWXMLHash#217]
**`Ambiguous use of 'Element'` error on Building Project**

**To Reproduce**
1. Adding SWXMLHash via cocoa pods
2. Build the project
3. Shows errors with *Ambiguous use of 'Element'*

**Screenshots**
![image](https://i.ibb.co/f4Rsc02/Screenshot-2019-08-29-at-1-15-40-PM.png)

**Environment:**
 - Xcode version: [e.g. Xcode 10]
 - Swift version: [e.g. 5.0.1]
 - OS running SWXMLHash: [e.g. MacOS 10.14.1 running Xcode]

**Comment by drmohundro** [comment]
Can you also post what your Podfile looks like? Thanks!

**Comment by drmohundro** [comment]
I think this is from an old version of SWXMLHash... if you're on Xcode 10 with Swift 5+, make sure your Podfile is targeting `5.0.0`. Like so:

```
pod 'SWXMLHash', '~> 5.0.0'
```

See also #140.

**Comment by rahul-apple** [comment]
@drmohundro 👍 It was an issue with old Xcode
