### ISSUE TITLE
Bundle id Error

### ISSUE THREAD

**Issue by raptorxcz** [drmohundro/SWXMLHash#218]
**Describe the bug**
Report from Apple:
ITMS-90806: CFBundleIdentifier collision - Each bundle must have a unique bundle identifier. The bundle identifier 'drmohundro.SWXMLHash' is used in the bundles '[SWXMLHash.framework, SWXMLHash.framework]'
App have iOS and watchOS target.

**To Reproduce**
1. make app with multiple platforms
2. upload it to AppStore

**Expected behavior**
No error from Apple

**Environment:**
 - Xcode version: Xcode 10.3
 - Swift version: 5.0.1
 - OS running SWXMLHash: MacOS 10.14.6 running Xcode

**Additional context**
Add `.${PLATFORM_NAME}` to end of bundle id

**Comment by drmohundro** [comment]
Hi @raptorxcz, thanks for the report... I did a little bit of digging and found an issue on the CocoaPods repo about this, see https://github.com/CocoaPods/CocoaPods/issues/9135. Just to double check, but are you using CocoaPods here?

There is also an Apple Developer Forums post about the same issue up at https://forums.developer.apple.com/thread/122048.

My current plan is to keep an eye on those threads to see what the recommended resolution is. There are also a few workarounds on that issue as well.

**Comment by raptorxcz** [comment]
Thanks for response. Unfortunately we use carthage and workaround is not applicable.

**Comment by drmohundro** [comment]
👍 gotcha... so this is happening with both CocoaPods and Carthage. Thanks for the clarification.

**Comment by drmohundro** [comment]
FYI, version `5.0.1` was just tagged and released. Thanks again for the report!
