### ISSUE TITLE
Version 5.0 not on cocoa pods?

### ISSUE THREAD

**Issue by stevensanborn** [drmohundro/SWXMLHash#223]
CocoaPods could not find compatible versions for pod "SWXMLHash":
  In Podfile:
    SWXMLHash (~> 5.0.0)

shows 4.9 on cocoa pods site

**Comment by drmohundro** [comment]
That is _weird_. I'm wondering if there was a caching issue with CocoaPods or something else going on. I can confirm that I saw `4.9.0` on the site as well, but when I tried to republish from here, I got the following:

```
[!] Unable to accept duplicate entry for: SWXMLHash (5.0.1)
```

Then I checked the site and it says `5.0.1` now.

Can you double check again on your side?

**Comment by stevensanborn** [comment]
i think its good now. Maybe i needed a repo update but it appears fine now. thanks.
