### ISSUE TITLE
How to get the string without backslash?

### ISSUE THREAD

**Issue by pandapancake** [drmohundro/SWXMLHash#227]
Hi, I'm not sure if it's swift problem or the pod. When I do 

````
XML.description 
````
it was returning escape character "\". I tried to do replacingOccurrences(of: "\", with: "") but no luck. I looked SOF can't find answers either.

**Comment by drmohundro** [comment]
Hi, I'm guessing you got this resolved, but this would be because of the content in the XML itself. SWXMLHash will return any string characters found and won't do any special parsing on anything that isn't XML characters. Everything else would be considered text.
