### ISSUE TITLE
Need to update SWXMLHash.swift to use FoundationXML

### ISSUE THREAD

**Issue by dbonner** [drmohundro/SWXMLHash#229]
SWXMLHash no longer builds with Swift 5.1.
To fix:
Edit SWXMLHash.swift
Add:
import FoundationXML
Replace:
Foundation.XMLParser
with
FoundationXML.XMLParser
The text replacement needs to be done 28 times in the file.
Please update for Swift 5.1

**Comment by drmohundro** [comment]
SWXMLHash already supports 5.1. Which version of SWXMLHash are you using right now and are you using it from CocoaPods or Carthage or something else?

**Comment by dbonner** [comment]
Apologies.  I just realised that you have updated SWXMLHash to import FoundationXML.  I was building sourcekite (https://github.com/vknabel/sourcekite), which in turn is dependant on SourceKitten (https://github.com/jpsim/SourceKitten, .package(url: "https://github.com/jpsim/SourceKitten", from: "0.24.0"),), which in turn is dependant on SWXMLHash (.package(url: "https://github.com/drmohundro/SWXMLHash.git", .upToNextMinor(from: "4.9.0")).  The version of the file SWXMLHash.swift that gets downloaded when I build sourcekite does not account for the change to needing the FoundationXML module.

**Comment by drmohundro** [comment]
Ah, gotcha. No worries at all, if I can help let me know!
