### ISSUE TITLE
Add Carthage Support

### ISSUE THREAD

**Issue by iamtomcat** [drmohundro/SWXMLHash#23]
I'm currently working on a fork to add this, but if you want to add it before then that would be killer.

**Comment by drmohundro** [comment]
I see the work you've already begun in your fork, so go for it! :+1:

I'm in the middle of working on the lazy loading support right now, so I'd welcome the help here.

**Comment by iamtomcat** [comment]
No worries, I'll try and roll through it this week sometime.

**Comment by neilco** [comment]
It already supports Carthage. Simply create a `Cartfile` pointing to this repo:

```
github "drmohundro/SWXMLHash"
```

and run `carthage update`.

**Comment by iamtomcat** [comment]
Do you have quick and nimble as dependencies in your cartfile already?
I haven't had a chance do this yet, but I think all this thing needs is a cartfile with quick and nimble added. I feel you should be able to build swxmlhash without having to add them as dependencies yourself, if you don't use them.

**Comment by neilco** [comment]
@iamtomcat No, you only need Nimble & Quick to run the tests. The library itself does not link those projects.

**Comment by iamtomcat** [comment]
True but carthage still tries to build them. But @drmohundro has added both nimble and quick to his project so they get built now. I was getting failures before because they were missing from the project so I needed a way to get around this either by getting the build target to not run tests as well. But since the projects are now included it's fixed. So I guess we can call this closed now. Thanks for letting me know.

**Comment by drmohundro** [comment]
Just so I'm clear because I haven't had a chance to work with Carthage yet, but is all that is necessary is to create a `Cartfile` with `github "drmohundro/SWXMLHash" >= 1.0` in it? I haven't changed how Quick and Nimble are included - they're still just git submodules. If everything is good, though, I'll go ahead and update the README to include those instructions as well to try to be proactive with the documentation.

And thanks for the help here!

**Comment by iamtomcat** [comment]
Hey sorry I didn't get back to you sooner. But yeah all you need to do is create a cartfile with the command you put, although I'd recommend  `~> 1.0` instead of `>=` although I suppose that's up the people using your library.

But in terms of quick and nimble, it seems that carthage now also will look at submodules and build them as well. I don't know if they have to be included in the project file or if it'll just build submodules carte blanche, I haven't had a chance to look into this yet. 

But yeah you should be able to say you support carthage at this point even with the other dependencies being built.

Also no worries about looking into this, glad I can help.

**Comment by drmohundro** [comment]
Great point about `~> 1.0` - I didn't even catch that!
