### ISSUE TITLE
check if element contain an attribute 

### ISSUE THREAD

**Issue by Moustafa2050** [drmohundro/SWXMLHash#233]
for example i have this element : 

<Fee CurrencyCode="USD"  Amount="733.11"   Purpose="22">
</Fee>

if i want to know if element Fee is contain the attribute Amount or not.
how can get this?

**Comment by drmohundro** [comment]
Hi @Moustafa2050 - I'm not sure what happened, but I'm not seeing any code snippets or anything... can you clarify your question?

**Comment by Moustafa2050** [comment]
Sorry for that and i don’t know what happened ,
my question is :
if  i have this element in XML format : 
	<Fee CurrencyCode="USD" Amount="733.11" Purpose="22"></Fee>

how can i check if element " Fee " has an attribute which name as example is " Amount "  or not?

**Comment by Moustafa2050** [comment]
Sorry for that and i don’t know what happened ,
my question is :
if i have this element in XML format :
`<Fee CurrencyCode="USD" Amount="733.11" Purpose="22"></Fee>`
how can i check if element " Fee " has an attribute which name as example is " Amount " or not?

**Comment by drmohundro** [comment]
I'm guessing you have multiple elements that are called `Fee` but not all have `Amount`?

Check out this small sample:

```swift
let issueXML = """
<Fees>
<Fee CurrencyCode="USD"></Fee>
<Fee CurrencyCode="USD" Amount="733.11" Purpose="22"></Fee>
</Fees>
"""

let issue = SWXMLHash.parse(issueXML)

let found = issue["Fees"]["Fee"].all.filter { idx in idx.element?.attribute(by: "Amount") != nil }

// only prints the one with the Amount attribute
print(found)
```

Does this help?

**Comment by Moustafa2050** [comment]
yes , that all  i need,

thank you so much .
