### ISSUE TITLE
Can not parse '&' - symbol

### ISSUE THREAD

**Issue by alikamts** [drmohundro/SWXMLHash#234]
Can't parse string which contains '&' operator
		"<NAME>Test Harbor Golf & My Club</NAME>"

example:

<DOCUMENT>
	<COURSE>
		<STATE>AK</STATE>
		<NAME>Hill Club</NAME>
	</COURSE>
	<COURSE>
		<STATE>AL</STATE>
		<NAME>Test Harbor Golf & My Club</NAME>
	</COURSE>
<DOCUMENT>

**Comment by drmohundro** [comment]
Hi @alikamts - check out #109 or #192 where a similar question was brought up.

The issue is that `&` isn't valid XML unless it is placed in a `CDATA` section. Otherwise, it would need to be escaped, as in `&amp;`.

Hope this helps!

**Comment by alikamts** [comment]
Ok got it thank you :-)
