### ISSUE TITLE
iOS 14 Compatibility Issue

### ISSUE THREAD

**Issue by atarana** [drmohundro/SWXMLHash#235]
Hi, I was trying to migrate my app on iOS 14 but I encountered a problem with this package. 
This problem causes the error: "Can't remove first element from an empty collection"

**Comment by drmohundro** [comment]
Hey, sorry the delayed reply - just trying to clarify, is this an error that occurs during runtime or are you seeing a compilation issue?

**Comment by atarana** [comment]
Hi, it was a runtime error. I have just realized that the problem was in the iOS 14 SDK. Thank you!
