### ISSUE TITLE
Self Closing Element handling

### ISSUE THREAD

**Issue by kriskelley63** [drmohundro/SWXMLHash#236]
Hello, first off thanks for the great XML parser. It has helped me out enormously! 

I'm having an issue with iterating through data when there is a self closing element and was wondering if you had any advice to handle it. 

In the first example it will end up skipping everything, in the second example  I have no issues and it grabs the data I need. 

```
<ENTRY>
         <NAME>Unbridled Halo</NAME>
         <DH_DQ_FLAGS/>
         <BREED>TB</BREED>
         <LAST_PP/>
         <WEIGHT>123</WEIGHT>
         <AGE>4</AGE>
</ENTRY>
// This has "LAST_PP" as a self closing


<ENTRY>
         <NAME>Our Prince</NAME>
         <DH_DQ_FLAGS/>
         <BREED>TB</BREED>
         <LAST_PP>
            <TRACK>
               <CODE>TAM</CODE>
               <NAME>TAMPA BAY DOWNS</NAME>
            </TRACK>
            <RACE_DATE>2020-04-19</RACE_DATE>
            <RACE_NUMBER>2</RACE_NUMBER>
            <OFL_FINISH>7</OFL_FINISH>
         </LAST_PP>
         <WEIGHT>123</WEIGHT>
         <AGE>4</AGE>

 </ENTRY>
```

Here is an example of the code I'm using.

  ```
          for names in xml["CHART"]["RACE"]["ENTRY"].all
//                capture and append data for each horse
            {
                var tempArray = [Any]()
                
               
                    
                   if let name = names["NAME"].element?.text,
                    let weight = names ["WEIGHT"].element?.text,
                    let age = names ["AGE"].element?.text,
                    let prevFIN = names ["LAST_PP"]["OFL_FINISH"].element?.text
                    
                {
                            
                tempArray.append(name)
                tempArray.append(Int(weight) ?? 0)
                tempArray.append(Int(age) ?? 0)            
                tempArray.append(Int(prevFIN) ?? 0)
                }

```
Thanks for any help you might have.

**Comment by kriskelley63** [comment]
Ok I figured out this is an issue with it not meeting all the requirements of the if statement. 

Any idea how to handle it? I tried splitting it into a different if but it's not working.

**Comment by drmohundro** [comment]
You're correct that the `if` block won't catch when the `LAST_PP` element is empty - because there is no `OFL_FINISH`. I'd recommend storing the `LAST_PP` element separately and handling it in its own method... so:

```swift
let lastPP = names["LAST_PP"]
```

Then, separately from checking name and weight, you can have code that handles the possibly empty LAST_PP element. If it is there, you can get it with:

```swift
lastPP["OFL_FINISH"].element
```

(disclaimer, I didn't try this out in a Playground, so I might have a few mistakes in the code, but the general idea should be fine)

**Comment by kriskelley63** [comment]
Thank you for the reply. I’ll play with that idea and see what happens

**Comment by drmohundro** [comment]
I'll go ahead and close this one, but feel free to respond if you still have any questions about it.
