### ISSUE TITLE
Turkish characters not recognized

### ISSUE THREAD

**Issue by kerimsari** [drmohundro/SWXMLHash#252]
Hello,

When i am trying to parse below xml with SWXMLHash. 
I get 2 children of XmlElement <Sonuc_Str>Başarılı</Sonuc_Str> instead of 1.
The problem is that the parser recognizes the turkish letter as separator.
So instead of parsing it as one children -> "Başarılı" it parses as 2 children 1 -> "Ba" 2 -> "şarılı"
I use utf8 which is the default encoding option for SWXMLHash

1. Take below xml

```xml
<CuzdanResult>
  <Sonuc>1</Sonuc>
  <Sonuc_Str>Başarılı.</Sonuc_Str>
  <E>
    <CL_L_Cuzdan>
      <ID>1000</ID>
      <Kredi>TurkPara - TRL - TRL</Kredi>
      <Cuzdan>TurkPara - TRL</Cuzdan>
    </CL_L_Cuzdan>
    <CL_L_Cuzdan>
      <ID>1112</ID>
      <Kredi>Yakıt - Z42</Kredi>
      <Cuzdan>Yakıt</Cuzdan>
    </CL_L_Cuzdan>
  </E>
</CuzdanResult>
```

2. Parse it with SWXMLHash
3. See error

I expect to have only one children for XmlElement `<Sonuc_Str>Başarılı.</Sonuc_Str>` instead of 2

![image](https://user-images.githubusercontent.com/2835912/114825990-9051c080-9dcf-11eb-92f5-c75bd253210a.png)

 - Xcode version Version 12.4 (12D4e)
 - Swift version 5.0
 - ios simulator 14.4

**Comment by drmohundro** [comment]
Hi @kerimsari... I tried to write a test to replicate what I'm understanding from your question but it looks like it is working as expected for me.

The test I'm using is:

```swift
    func testFromQuestion() {
        let xml = """
            <CuzdanResult>
              <Sonuc>1</Sonuc>
              <Sonuc_Str>Başarılı.</Sonuc_Str>
              <E>
                <CL_L_Cuzdan>
                  <ID>1000</ID>
                  <Kredi>TurkPara - TRL - TRL</Kredi>
                  <Cuzdan>TurkPara - TRL</Cuzdan>
                </CL_L_Cuzdan>
                <CL_L_Cuzdan>
                  <ID>1112</ID>
                  <Kredi>Yakıt - Z42</Kredi>
                  <Cuzdan>Yakıt</Cuzdan>
                </CL_L_Cuzdan>
              </E>
            </CuzdanResult>
        """
        
        let parser = SWXMLHash.parse(xml)
        
        let count = parser["CuzdanResult"]["Sonuc_Str"].all.count
        
        XCTAssertEqual(count, 1)
    }
```

![image](https://user-images.githubusercontent.com/43072/114949798-645a2d80-9e17-11eb-8ae7-9aab00e6b271.png)

Am I misunderstanding your question? Or could you drop a code snippet to help me understand?

Thanks and hope I can help you out!

**Comment by kerimsari** [comment]
Hi @drmohundro i had to make modifications to func parser(_ parser: Foundation.XMLParser, foundCharacters string: String) method to accumulate 2 children into one value....

If not SWXMLHash.parse returns 2 children....
Am i doing something wrong in the configuration?

Actually the problem is solved with a little bit of hack...

Please see below

 func parser(_ parser: Foundation.XMLParser,
                didStartElement elementName: String,
                namespaceURI: String?,
                qualifiedName qName: String?,
                attributes attributeDict: [String: String]) {

        let currentNode = parentStack
                .top()
                .addElement(elementName, withAttributes: attributeDict, caseInsensitive: self.options.caseInsensitive)

        accumulatedNodeValue = String()
        parentStack.push(currentNode)
    }

    func parser(_ parser: Foundation.XMLParser, foundCharacters string: String) {
        accumulatedNodeValue += string
    }

    func parser(_ parser: Foundation.XMLParser,
                didEndElement elementName: String,
                namespaceURI: String?,
                qualifiedName qName: String?) {

        let current = parentStack.top()
        current.addText(accumulatedNodeValue)

        parentStack.drop()
    }


Thank you

**Comment by drmohundro** [comment]
@kerimsari I'm not sure I'm following when you say you're seeing 2 children under the `Sonuc_Str` element... 

See below: if I query `parser["CuzdanResult"]["Sonuc_Str"].element!.text` it just comes back with the single `"Başarılı."` string. Does that not work for you?

```
    func testFromQuestion() {
        let xml = """
            <CuzdanResult>
              <Sonuc>1</Sonuc>
              <Sonuc_Str>Başarılı.</Sonuc_Str>
              <E>
                <CL_L_Cuzdan>
                  <ID>1000</ID>
                  <Kredi>TurkPara - TRL - TRL</Kredi>
                  <Cuzdan>TurkPara - TRL</Cuzdan>
                </CL_L_Cuzdan>
                <CL_L_Cuzdan>
                  <ID>1112</ID>
                  <Kredi>Yakıt - Z42</Kredi>
                  <Cuzdan>Yakıt</Cuzdan>
                </CL_L_Cuzdan>
              </E>
            </CuzdanResult>
        """
        
        let parser = SWXMLHash.parse(xml)
        
        let count = parser["CuzdanResult"]["Sonuc_Str"].all.count
        
        XCTAssertEqual(count, 1)
        
        let txt = parser["CuzdanResult"]["Sonuc_Str"].element!.text
        
        XCTAssertEqual(txt, "Başarılı.")
    }
```

**Comment by kerimsari** [comment]
Hi,

Could you try the code below?

import Foundation
public class CL_Res_Cuzdan{
     public var Sonuc : Int = 0
     public var Sonuc_Str : String = ""
     public var E : [CL_L_Cuzdan] = [] 
}

public func CL_Res_CuzdanFromXMLString(xmlToParse: String) -> CL_Res_Cuzdan {

        let xml = SWXMLHash.config {
            config in
            config.encoding = .utf8
            config.caseInsensitive = true
            config.shouldProcessLazily = false
        }.parse (xmlToParse)

        let xmlRoot = xml.children.first
        let xmlBody = xmlRoot?.children.last
        let xmlResponse: XMLIndexer? = xml.children.first?.children.first?.children.first
        let xmlResult0: XMLIndexer? = xmlResponse?.children.last
        var strVal = ""
        var elemName = ""
        var returnValue: CL_Res_Cuzdan = CL_Res_Cuzdan ()
        if elemName == "" {

            let itemCount1: Int = (xmlResult0?.children.count)!
            for i1 in 0..<itemCount1 {
                let xmlResult1: XMLIndexer? = xmlResult0?.children[i1]
                let elem1: XMLElement? = xmlResult1!.element

                strVal = ""

                if elem1?.children.first is TextElement {
                    let elemText1: TextElement = elem1?.children.first as! TextElement
                    strVal = elemText1.text
                }

                elemName = elem1!.name

                if elemName == "Sonuc" {
                    returnValue.Sonuc = strVal.toInt ()!
                } else if elemName == "Sonuc_Str" {
                    returnValue.Sonuc_Str = strVal
                } else if elemName == "E" {

                    let itemCount2: Int = (xmlResult1?.children.count)!
                    for i2 in 0..<itemCount2 {
                        let rItem2 = CL_L_Cuzdan ()
                        let xmlResult_Parent2: XMLIndexer? = xmlResult1?.children[i2]
                        let childCount2: Int = (xmlResult_Parent2?.children.count)!
                        for j2 in 0..<childCount2 {

                            let xmlResult2: XMLIndexer? = xmlResult_Parent2?.children[j2]
                            let elem2: XMLElement? = xmlResult2?.element
                            strVal = ""
                            if elem2?.children.first is TextElement {
                                let elemText: TextElement = elem2?.children.first as! TextElement
                                strVal = elemText.text
                            }

                            elemName = elem2!.name

                            if elemName == "ID" {
                                rItem2.ID = strVal
                            } else if elemName == "Kredi" {
                                rItem2.Kredi = strVal
                            } else if elemName == "Cuzdan" {
                                rItem2.Cuzdan = strVal
                            }

                        }
                        returnValue.E.append (rItem2)

                    }
                }
            }
        }
        return returnValue
    }

**Comment by drmohundro** [comment]
@kerimsari I don't think the code snippet includes enough for me to run it... it is failing because it doesn't have the `CL_L_Cuzdan` class/struct. In addition, it is expecting more XML than just the snippet. I'd need at least the other struct plus an XML sample that has the rest of the structure at least.
