### ISSUE TITLE
Module 'SWXMLHash' has no member named 'config

### ISSUE THREAD

**Issue by imranrasheeddeveloper** [drmohundro/SWXMLHash#253]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Environment:**
 - Xcode version: [e.g. Xcode 10]
 - Swift version: [e.g. 5.0.1]
 - OS running SWXMLHash: [e.g. MacOS 10.14.1 running Xcode]

**Additional context**

**Comment by drmohundro** [comment]
Hi @imranrasheeddeveloper - I'm not seeing the issue details actually filled out, it looks like it is still just using the template... the title suggests that you're seeing an issue related to `'SWXMLHash' has no member named 'config'`, though.

- How do you have SWXMLHash installed?
- Which version are you using?
- Which Xcode version?
- Which Swift version?

Do you have a repro set up somewhere that I could look at?

**Comment by imranrasheeddeveloper** [comment]
swift version 5 
Xcode 12.4

![Screenshot 2021-11-10 at 11 37 50 PM](https://user-images.githubusercontent.com/51517176/141173235-5b3de9dc-21da-460c-9c61-96512cd87db7.png)

`fileprivate func parse() throws -> Group {
        let config = SWXMLHash.config { config in
            config.shouldProcessNamespaces = true
        }
        let parsedXml = config.parse(xmlString)

        var svgElement: SWXMLHash.XMLElement?
        for child in parsedXml.children {
            if let element = child.element {
                if element.name == "svg" {
                    svgElement = element
                    try prepareSvg(child.children)
                    break
                }
            }
        }
        let layout = svgElement != nil ? try parseViewBox(svgElement!) : nil
        try parseSvg(parsedXml.children)
        let root = layout != nil ? SVGCanvas(layout: layout!, contents: nodes) : Group(contents: nodes)
        if let opacity = svgElement?.attribute(by: "opacity") {
            root.opacity = getOpacity(opacity.text)
        }
        return root
    }
`

**Comment by drmohundro** [comment]
If you're using the latest version of SWXMLHash, the entry class has been renamed from `SWXMLHash` to `XMLHash` - see the release up at https://github.com/drmohundro/SWXMLHash/releases/tag/6.0.0.

This was done to fix a specific scenario mentioned in https://github.com/drmohundro/SWXMLHash/issues/242.

I think that might be the fix here. So, in your case, the code should instead look like:

```swift
    fileprivate func parse() throws -> Group {
        let config = XMLHash.config { config in
            config.shouldProcessNamespaces = true
        }
        let parsedXml = config.parse(xmlString)

        var svgElement: XMLHash.XMLElement?
        for child in parsedXml.children {
            if let element = child.element {
                if element.name == "svg" {
                    svgElement = element
                    try prepareSvg(child.children)
                    break
                }
            }
        }
        let layout = svgElement != nil ? try parseViewBox(svgElement!) : nil
        try parseSvg(parsedXml.children)
        let root = layout != nil ? SVGCanvas(layout: layout!, contents: nodes) : Group(contents: nodes)
        if let opacity = svgElement?.attribute(by: "opacity") {
            root.opacity = getOpacity(opacity.text)
        }
        return root
    }
```

**Comment by drmohundro** [comment]
If you're using the latest version of SWXMLHash, the entry class has been renamed from `SWXMLHash` to `XMLHash` - see the release up at https://github.com/drmohundro/SWXMLHash/releases/tag/6.0.0.

This was done to fix a specific scenario mentioned in https://github.com/drmohundro/SWXMLHash/issues/242.

I think that might be the fix here. So, in your case, the code should instead look like:

```swift
    fileprivate func parse() throws -> Group {
        let config = XMLHash.config { config in
            config.shouldProcessNamespaces = true
        }
        let parsedXml = config.parse(xmlString)

        var svgElement: XMLHash.XMLElement?
        for child in parsedXml.children {
            if let element = child.element {
                if element.name == "svg" {
                    svgElement = element
                    try prepareSvg(child.children)
                    break
                }
            }
        }
        let layout = svgElement != nil ? try parseViewBox(svgElement!) : nil
        try parseSvg(parsedXml.children)
        let root = layout != nil ? SVGCanvas(layout: layout!, contents: nodes) : Group(contents: nodes)
        if let opacity = svgElement?.attribute(by: "opacity") {
            root.opacity = getOpacity(opacity.text)
        }
        return root
```

**Comment by drmohundro** [comment]
I'm closing the issue. If you're still having issues, please feel free to comment or re-open.
