### ISSUE TITLE
Fail theverge parse

### ISSUE THREAD

**Issue by bubudrc** [drmohundro/SWXMLHash#254]
**Describe the bug**
Trying to parse the feed from the verge: https://www.theverge.com/rss/index.xml I couldn't found any way to deserialize

**To Reproduce**
I'm created 2 struct:

```
struct Channel: XMLIndexerDeserializable {
    var title: String?
    var entries: [Item]?

    static func deserialize(_ node: XMLIndexer) throws -> Channel {
        return try Channel (
            title: node["title"].value(),
            entries: node["entry"].value()
        )
    }
}

struct Item: XMLIndexerDeserializable {
    let title: String?
    let link: String?
   
    static func deserialize(_ node: XMLIndexer) throws -> Item {
        return try Item (
            title: node["title"].value(),
            link: node["link"].value()
        )
    }
}
```

And tried different approaches, but nothing works:
```
let feedChannel: Channel = try xml["feed"].value()
let itemsTest: [Item] = try xml["feed"]["entry"].value()
```

I'm always get:

> Serialization error occurred: The operation couldn’t be completed. (SWXMLHash.XMLDeserializationError error 1.)

What could be wrong?

BTW:
I'm tested other XML and the parsing works correctly

**Comment by drmohundro** [comment]
That's strange... it worked for me.

Here's what I did:

```sh
# these commands were done in the cloned SWXMLHash directory locally for me
wget https://www.theverge.com/rss/index.xml -O feed.xml
mv feed.xml Tests/SWXMLHashTests/
```

Then I added the following unit test to try it out which passed for me:

```swift
    func testStuff() {
        do {
            let path = NSString.path(withComponents: NSString(string: #file).pathComponents.dropLast() + ["feed.xml"])
            let data = try! Data(contentsOf: URL(fileURLWithPath: path))
            let xml = XMLHash.parse(data)
            
            let feedChannel: Channel = try xml["feed"].value()
            let itemsTest: [Item] = try xml["feed"]["entry"].value()
            
            XCTAssertNotNil(feedChannel)
            XCTAssertNotNil(itemsTest)
        } catch {
            XCTFail("wuh oh")
        }
    }
```

See screenshot of passing test below:

![image](https://user-images.githubusercontent.com/43072/148289170-23d337bf-3e2f-4283-864a-67a392d8d4bf.png)

How are you getting the index.xml file?

**Comment by bubudrc** [comment]
Hey @drmohundro, before all sorry to bother you and thanks for your help.

Sadly, you're right. After you solution, I'm changed a little my parsing method and it's working great now. Sorry for the mistake.

So, before to close the tread, I will like to ask you why the extension date that is on the readme, doesn't work:
![Screen Shot 2022-01-05 at 20 29 56](https://user-images.githubusercontent.com/619159/148304629-e1cfe362-74f6-4641-9222-8d62c0dd6ec2.png)

Thanks in advance

**Comment by drmohundro** [comment]
@bubudrc oh good catch! The docs are wrong! I'll get that fixed. And as I look at it, the `dateFormat` call is incorrect, too. I fixed the README in 2aa4a48d1ff95cf3a95e9dd202b281daa12025dc.

The gist is that it should instead be:

```diff
extension Date: XMLElementDeserializable, XMLAttributeDeserializable {
    public static func deserialize(_ element: XMLElement) throws -> Date {
        let date = stringToDate(element.text)

        guard let validDate = date else {
            throw XMLDeserializationError.typeConversionFailed(type: "Date", element: element)
        }

        return validDate
    }

    public static func deserialize(_ attribute: XMLAttribute) throws -> Date {
        let date = stringToDate(attribute.text)

        guard let validDate = date else {
            throw XMLDeserializationError.attributeDeserializationFailed(type: "Date", attribute: attribute)
        }

        return validDate
    }

+   public func validate() throws {
+       // empty validate... only necessary for custom validatio logic after parsing
+   }
+
    private static func stringToDate(_ dateAsString: String) -> Date? {
        let dateFormatter = DateFormatter()
+       dateFormatter.dateFormat = "EEEE, dd MMMM yyyy HH:mm:ss SSS"
-       dateFormatter.dateFormat = "EEE, dd MMM yyyy HH:mm:ss zzz"
        return dateFormatter.date(from: dateAsString)
    }
}
```

Thanks for the heads up on the bug in the README!

**Comment by bubudrc** [comment]
AWESOME!!! you're the best.

Thanks for this great library and all your help :)

**Comment by drmohundro** [comment]
Happy to help!
