### ISSUE TITLE
Child-Elements has empty Array

### ISSUE THREAD

**Issue by freakontour** [drmohundro/SWXMLHash#255]
**Describe the bug**
I am trying to read an XML File. I can access to "actuatorDescription" and "groupPara", but if I want to go deeper in the structure I am always getting a empty array back. I didn't understand where is the failure.
Can you please explain me what is happened.

I am calling different Print-Function to reach the Data but only these two are working:
`print(try xml["actuatorDescription"].all)
 print(try xml["actuatorDescription"]["groupPara"].all)`

When I am going deeper with following prints the results are an empty array
`try xml["actuatorDescription"]["groupPara"]["paraList"].children`

XML-File

File-Structure from Debugger:
![image](https://user-images.githubusercontent.com/87744952/152879642-f83229c5-0434-4f17-8ba7-ce0d8726e607.png)
[327-MB_01.txt](https://github.com/drmohundro/SWXMLHash/files/8019073/327-MB_01.txt)

**Comment by drmohundro** [comment]
Hi @freakontour, good question. I think I know what is going on... as far as I can tell, the `groupPara` element is always structure like this:

- groupPara
  - paraName
  - layout
  - paraList

Is that right? Maybe some of those elements are optional. Either way, I think you'd need to enumerate those values by looping each `groupPara` element and then grabbing the `paraList` off of it.

So something like this:

```swift
        for groupPara in xml["actuatorDescription"]["groupPara"].all {
            let paraList = groupPara["paraList"]
            for child in paraList.children {
                print(child.element?.name)
            }
        }
```
