### ISSUE TITLE
"'XMLElement' is ambiguous for type lookup in this context" when compiling for Mac Catalyst

### ISSUE THREAD

**Issue by GerdC** [drmohundro/SWXMLHash#256]
**Describe the bug**
Compiler complains about "'XMLElement' is ambiguous for type lookup in this context" when compiling for Mac Catalyst

**To Reproduce**
-  In an iOS project target, enable Mac Catalyst
- Compile code that uses XMLElement

**Expected behavior**
compiles without error message

**Environment:**
 - Xcode version: 13.2.1
 - OS running SWXMLHash: MacOS 12.2.1 running Xcode

**Additional context**
appears to be a known problem when directly compiling for MacOs. XMLElement Sourcecode says
// Workaround for "'XMLElement' is ambiguous for type lookup in this context" error on macOS.

**Comment by drmohundro** [comment]
Confirmed - I put together a quick repro of it up at https://github.com/drmohundro/swxmlhash-test-xmlelement-catalyst-repro.

That being said, it is possible to get around it by scoping the `XMLElement` with `SWXMLHash.XMLElement`. See https://github.com/drmohundro/swxmlhash-test-xmlelement-catalyst-repro/commit/07bad9daf75a469f3b9cb96b57ce6c4473172bcd - that compiles for me.

Does that solve your issue?

**Comment by GerdC** [comment]
Yes, replacing `XMLElement` with `SWXMLHash.XMLElement` works for me

**Comment by drmohundro** [comment]
Great! I'll close this as the only alternative I'm aware of would be a rename... and there have already been multiple renames! (#140, #242).
