### ISSUE TITLE
Method for inner Child

### ISSUE THREAD

**Issue by toseefkhilji** [drmohundro/SWXMLHash#257]
Thanks for awesome Lib.
It's really helping.

I have XML like
```
<?xml version="1.0" encoding="utf-8"?>
<soap:Envelope
    xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <soap:Body>
        <GetAllMessageListResponse
            xmlns="http://tempuri.org/">
            <GetAllMessageListResult>
                <ArrayOfCtMessageMst
                    xmlns:xsd="http://www.w3.org/2001/XMLSchema"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xmlns="">
                    <ctMessageMst>
                        <MessageID>1</MessageID>
                        <TitleName>SYSTEM ERROR</TitleName>
                        <ProductID>0</ProductID>
                        <MessageText>System Error</MessageText>
                        <MessageType>E</MessageType>
                        <Date>2014-07-09T01:39:28.81</Date>
                    </ctMessageMst>
                    <ctMessageMst>
                        <MessageID>2</MessageID>
                        <TitleName>SIGN UP - User successfully created.</TitleName>
                        <ProductID>0</ProductID>
                        <MessageText>User successfully created</MessageText>
                        <MessageType>S</MessageType>
                        <Date>2014-07-17T03:54:55.35</Date>
                    </ctMessageMst>
                </ArrayOfCtMessageMst>
            </GetAllMessageListResult>
        </GetAllMessageListResponse>
    </soap:Body>
</soap:Envelope>
```
and i am parsing lt like.

```
let xml = XMLHash.parse(stringdata)
            let messges: [Message] = try xml["soap:Envelope"]["soap:Body"]["GetAllMessageListResponse"]["GetAllMessageListResult"]["ArrayOfCtMessageMst"]["ctMessageMst"].value()
```

And it's working as design.

but.

**Is your feature request related to a problem? Please describe.**
I am thinking such method the travers through inner childs and return me specfic name.
something like

**`let message = xml.findInnerChild("ArrayOfCtMessageMst")`**

so we don't have to write whole `xml["soap:Envelope"]["soap:Body"]["GetAllMessageListResponse"]["GetAllMessageListResult"]["ArrayOfCtMessageMst"]["ctMessageMst"]` path.

**Describe the solution you'd like**
Some recursive method that check it's inner child.

**Describe alternatives you've considered**
No

**Additional context**

**Comment by drmohundro** [comment]
I understand the request, but the concern I've got is for cases with XML like this:

```xml
<libraries>
	<library>
		<name>Downtown Library</name>
		<address>123 Street</address>
		<books>
			<book>
				<name>A Good Book</name>
				<isbn>123-123</isbn>
			</book>
		</books>
	</library>
	<library>
		<name>Suburb Library</name>
		<address>987 Street</address>
		<books>
			<book>
				<name>Another Good Book</name>
				<isbn>abc-abc</isbn>
			</book>
		</books>
	</library>
</libraries>
```

What would the following code return?

```swift
let name: [String] = xml.findInnerChild("name")
```

The `name` element is in two different places because there aren't any rules around uniqueness of XML element names. The `findInnerChild` method would have to recurse the entire XML hierarchy and it wouldn't be able to safely deserialize because the returned types could be a variety of types.

Does that make sense?

**Comment by toseefkhilji** [comment]
I understand you point.

**Comment by drmohundro** [comment]
I've occasionally thought about putting up a directory or repository of useful/helpful snippets to handle things like this - maybe things that don't necessarily belong in the core, but that many users would find helpful. Bare minimum, I could help come up with the function that would give you what you're looking for.

Would that be useful?

**Comment by toseefkhilji** [comment]
@drmohundro : Yes, That will help surely.

**Comment by drmohundro** [comment]
See if this approach works for you:

```swift
extension XMLIndexer {
    func findInnerChild(_ elemName: String) -> XMLIndexer? {
        for elem in self.children {
            if (elem.element?.name == elemName) {
                return elem
            }
            
            let match = elem.findInnerChild(elemName)
            if match != nil {
                return match
            }
        }
        
        return nil
    }
}
```

I added the following test and it seems to work for me (in https://github.com/drmohundro/SWXMLHash/blob/main/Tests/SWXMLHashTests/XMLParsingTests.swift).

```swift
    func testShowingInnerChild() {
        let book = xml!.findInnerChild("book")
        XCTAssertEqual(book![0]["author"].element?.text, "Gambardella, Matthew")
        XCTAssertNotNil(book)
    }
```

**Comment by drmohundro** [comment]
I'll close this one for now - I might still create a separate helper repo, though.
