### ISSUE TITLE
Carthage using builds unnecessary dependencies

### ISSUE THREAD

**Issue by tomassliz** [drmohundro/SWXMLHash#28]
Nimble and Quick dependencies are builded too, because they have shared scheme in project. But I want to use SWXMLHash and Nimble or Quick are worthless for me. And it takes some time when more frameworks is builded.

**Comment by drmohundro** [comment]
I'm not using Carthage at the moment, so forgive my ignorance with this... is the main thing that is necessary to fix this to create two schemes? One for strictly SWXMLHash and one for the tests? Does the fact that I'm using Quick/Nimble as submodules affect this?

**Comment by tomassliz** [comment]
Sorry, this should not be a critic. I'm grateful for this framework.

Carthage builds only shared schemes for all targets in project and these targets must be of type "dynamic framework".

So you need to remove Quick and Nimble targets from all shared schemes. Or you can use [Cartfile.private](https://github.com/Carthage/Carthage/blob/master/Documentation/Artifacts.md#cartfileprivate), but I don't have any experience with this.

**Comment by drmohundro** [comment]
No worries, I just wanted to understand the issue - thanks for helping out! There was another Carthage related issue (see #23) with some comments related to this and I think that's what they were talking about.

**Comment by tomassliz** [comment]
Yes, it's same thing.

**Comment by iamtomcat** [comment]
I can maybe take a look at this tomorrow night. I think since you're not using carthage in the first place that a private file won't really change anything. You should be able to maybe unshare the testing target or something along those lines.

**Comment by iamtomcat** [comment]
Decided to take a look into this now. But it seems that carthage probably does a recursive checkout, which means that it pulls down your dependencies. Once they exist and since they are available in the workspace they are built as well. I'm not sure of a way to get around this atm.

**Comment by drmohundro** [comment]
I did a little more research on this (again, having not used Carthage just yet) and it looks I definitely should look into migrating my current usage of Quick/Nimble away from git submodules. My other options for Quick/Nimble seem to be either using CocoaPods (with a test target specified) or using Carthage (with a `Cartfile.private`).

I'm open to suggestions between the two. (or alternatives!) Any thoughts?

**Comment by iamtomcat** [comment]
It depends on how you like your dependency management I suppose. Cocoapods instantly turned me off because it modifies your project file. But if you're just going to use it for your dependencies it might not be a bad idea because people using carthage won't see it. But if you like the way carthage works, then a private file would be good as well. I think it's up to you and how you'd like to have your dependencies handled.

**Comment by jspahrsummers** [comment]
If you don't want to modify your Cartfiles, you can just disable tests being built with your main target (from Xcode's scheme editor). Since Carthage doesn't build for testing, and would then skip your tests' dependencies, no other changes should be necessary.

**Comment by drmohundro** [comment]
I just committed https://github.com/drmohundro/SWXMLHash/commit/0cb500a05f500d9f70eba6d92403cc704935b66b to move away from git submodule support over to Carthage for Quick and Nimble. They're only specified in the `Cartfile.private` file, too.

I believe this should resolve the issue, but I'll keep this open for a few days in case there are still some problems.

There were some references earlier to a shared scheme as well - I didn't change anything about that, so there still may be some issues. I appreciate everyone's help in getting this knocked out!

**Comment by tomassliz** [comment]
I tried version 1.0.1 and everything is fine now. Thank you for solving!

**Comment by drmohundro** [comment]
:+1: great!
