### ISSUE TITLE
Element not found for empty XML node

### ISSUE THREAD

**Issue by CoryFoy** [drmohundro/SWXMLHash#280]
**Describe the bug**
We have XML documents which contain empty elements but we still need to check are present. When we reference the element in the XMLIndexer and try to get the `element` it returns nil, so we're having to resort to using whether the `description` is present

**To Reproduce**
1. Given the following XML: `<event><detail><archive /></detail></event>` parse it with `XMLHash.parse`
2. Access the following: `result["event"]["detail"]["archive"].element`

**Expected behavior**
I expect it to not be nil, but it comes back as nil. It's possible I'm misunderstanding what the goal of `element` is in the accessor, but I didn't see another way of checking for its presence.

**Environment:**
 - Xcode version: 15.4
 - Swift version: 5
 - OS running SWXMLHash: MacOS

**Comment by drmohundro** [comment]
Thanks for the bug report! So... I just added this test to see if I could reproduce the issue, but this test passes for me locally...

```swift
    func testForBugReported() {
        let testXml = """
        <event><detail><archive /></detail></event>
        """
        
        let parser = XMLHash.parse(testXml)
        
        XCTAssertNotNil(parser["event"]["detail"]["archive"].element)
        XCTAssertNil(parser["event"]["detail"]["notThere"].element)
    }
```

I've also added a branch for the test, but I'm waiting for the build to report back... I have a matrix test set up that may fail because of the latest OS versions, but it still looks okay at the moment.

Can you confirm that my test is checking what you're asking about?

**Comment by CoryFoy** [comment]
Well then! Yes, that's exactly the test I was running into the issue with. I even tried it with the xml namespaces and some other things, and now I can repro it. Clearly it was an issue at some point for me because I had workarounds in my code for it - but now I'm wondering if some source thing was maybe the actual issue and not the parser at all!

I appreciate you checking on this, and sorry for the errant bug report. I'm going to close this, but if I can test anything else for you please let me know!

**Comment by drmohundro** [comment]
No worries, glad we could figure it out! If you see the issue again, I'm happy to try to help narrow down what is going on. There have been some strange issues in the past so who knows!
