### ISSUE TITLE
Add support for Swift Testing...

### ISSUE THREAD

**Issue by woolie** [drmohundro/SWXMLHash#281]
**Is your feature request related to a problem? Please describe.**
When using Swift Testing in Swift 6, trying to do an `#expect(throws: XMLDeserializationError.***) {}` fails to compile due to a requirement of Error types to be equatable using the `#expect` macro, which I assume is needed for enums with associated values (since I have not seem this problem crop us when I have used it without enum associated values).

**Describe the solution you'd like**
I'd like equatable to be added for the errors enums

**Describe alternatives you've considered**
For now I am commenting out my testing in those areas where I am expecting errors thrown.

**Additional context**

**Comment by drmohundro** [comment]
Interesting... I haven't looked into Swift 6 compatibility yet, but there are some issues. It looks like SWXMLHash can build under Swift 6, but when I try to run the tests under it, those just crash.

I'll have to do some research into what will be needed for full Swift 6 support.

**Comment by drmohundro** [comment]
I've got a draft PR up at https://github.com/drmohundro/SWXMLHash/pull/283... branch is `feat/swift-6-support`. `swift test` is still failing for me, but I don't know if that is for a different reason. I think the `#expects(throws: XMLDeserializationError.self)` _should_ work, though I'm not positive yet... I'm still working through getting the branch tested.

Feel free to give it a try to see if it works for you, though.

**Comment by woolie** [comment]
It doesn't work for me.

```
	@Test func shouldThrowWhenConvertingEmptyToNonOptional() async throws {
		#expect(throws: XMLDeserializationError.nodeHasNoValue) {
			try (parser!["root"]["empty"].value() as ComplexItem)
		}
	}
```

Still has an issue with the XMLDeserializationError.nodeHasNoValue not having an equatable conformance.

**Comment by woolie** [comment]
Nevermind, read the code woolie. It works fine with your changes.

**Comment by drmohundro** [comment]
That's great, thanks for verifying! I'll plan to merge and get a major version released with this once the latest Xcode is stable... I've got the builds mostly green, but they're inconsistent because of the Xcode betas I think.
