### ISSUE TITLE
Getting entire HTML between opening and closing tag.

### ISSUE THREAD

**Issue by pawelnr1** [drmohundro/SWXMLHash#33]
My question might be a little bit lame but I just can't figure it out. How to get everything between opening and closing html tag?
For example now I have 
`let b = xml["everything"]["news"][i]["content"].element?.text`
which returns string: 
`Click this  for super cool news. `
and I would like it to return 
`Click this <a href="https://www.link.com">link</a> for super cool news.`
Thank you for help.

**Comment by drmohundro** [comment]
If I'm understanding you correctly, you're interested in something like an `innerHTML` type of behavior. Can you try calling `description` on the parent element? So, something like:

```
let b = xml["everything"]["news"][i]["content"].description
```

**Comment by pawelnr1** [comment]
Yep, `.description` is  what I needed. Thanks.

**Comment by drmohundro** [comment]
Happy to help!

**Comment by pawelnr1** [comment]
I believe there is something wrong with `.description`. 
When my <content> is like this:
` <content> Here is a cool thing <a href="google.com">A</a> and second cool thing <a href="fb.com">B</a></content>`
 `.description` returns me 
` <content> <a href="google.com">A</a><a href="fb.com">B</a></content>`
and I was expecting
 ` Here is a cool thing <a href="google.com">A</a> and second cool thing <a href="fb.com">B</a>`

**Comment by drmohundro** [comment]
Okay, it sounds like pure text content isn't getting returned in this situation - I'll have to do some more digging on this (as well as add a test case).

**Comment by drmohundro** [comment]
I'm tagging this with "help wanted" - I'd still love to get around to fixing this, but if someone has some free time to try to knock this out, I'd welcome the assistance.

To try to help out, here is a quick test I wrote (which would currently fail with existing behavior) to show what the expectations are...

```swift
describe("mixed text with XML elements") {
  var xml: XMLIndexer?

  beforeEach {
    let xmlContent = "<everything><news><content>Here is a cool thing <a href="google.com">A</a> and second cool thing <a href="fb.com">B</a></content></news></everything>"
    xml = SWXMLHash.parse(xmlContent)
  }

  it("should be able to get all contents inside of an element") {
    // fails because "Here is a cool thing " and " and second cool thing " are getting lost
    expect(xml!["everything"]["news"]["content"].description).to(equal("Here is a cool thing <a href=\"google.com\">A</a> and second cool thing <a href=\"fb.com\">B</a>"))
  }
}
```

Currently, the structure in memory is single elements with child elements and values... I think this would require having a concept of something like pure text elements as children, too. I have *no* idea what it would look like to index in to get this content, though! That's honestly the more difficult thing to solve.

**Comment by moehrenzahn** [comment]
I'm sorry to bump this without really contributing to the issue, but I am running into the same problem of mixed text with XML elements.

I can get the text and the XML elements separately but I can't find a way to detect where in the base text the XML elements belong.

Do you have any idea for a workaround?

(I love this project by the way, thanks for all your work!)

**Comment by drmohundro** [comment]
@moehrenzahn I'm glad the project has been helpful!

I don't really know of a good workaround at the moment - at the very least, I think there would need to be the concept of a property like `xml` or `innerXml` instead of just `text`. Otherwise just grabbing `text` would be odd in terms of knowing if the text occurred before the XML element showed up or not.

For example, given this XML snippet:

```xml
<foo>
  before
  <name>John</name>
  after
</foo>
```

What should `xml["foo"].text` return? `"before<name>John</name>after"`? Or `"beforeafter"` without any concept of the `name` element? I could see text possibly returning an array of text elements (i.e. [0] = "before", [1] = "after"), but I'm not sure.

If you have any thoughts on what the API would look like for this, that would be helpful.

**Comment by moehrenzahn** [comment]
I think just returning an array of text elements would not be great for every edge case. Consider these:

```
<foo>
  <name>Julia</name
  This is a
  <name>John</name>
  test string.
</foo>
```

and

```
<foo>
  This is a  
  <name>Julia</name
  <name>John</name>
  test string.
</foo>
```

These cases would be ambiguous. The `name`arrays would both be `["This is a", "test string."]`.

I would prefer one of the following:

- An `innerHTML`-type element that returns the raw XML as a string. This would give lots of flexibility and be easy to understand. Most of the time the mixed XML tags will be html anyways.
- An element that returns a mixed array of text and XML elements. Something like `[xml["name"->"Julia"], "This is a", xml["name"->"John"], "test string."]`. This would be useful, but possibly unwieldy in practice.

**Comment by drmohundro** [comment]
Great point regarding the array being ambiguous. I think it would definitely be doable to do something like `innerHTML` / `innerXML` - my only concern there is that it would be difficult to continue parsing. If it just a matter of getting the contents without further processing, though, that could work. That was the original intent behind the `description` property, but it doesn't handle this scenario right now. If I can find some time, I'll try to research this.

**Comment by drmohundro** [comment]
Good news! I just opened #62 that should handle this. I'd appreciate some additional testing and/or input before I merge this into master - I had to rewire how text is handled (before was just a string property, now is a new `TextElement` type). All of my specs are passing, but you can't be too careful.

To test locally, you can just pull down that branch and copy/paste the `SWXMLHash.swift` file into your codebase.

If I don't hear anything in a few days, I'll go ahead and merge this in, though.

Thanks again for reporting this and also for your patience!

**Comment by moehrenzahn** [comment]
Awesome! In my preliminary tests this does exactly what it should do. Thanks a bunch for your effort!

**Comment by drmohundro** [comment]
I just pushed `2.1.0` which includes this fix (both CocoaPods and Carthage) - thanks again!
