### ISSUE TITLE
Cannot compile with Xcode 6.1.1

### ISSUE THREAD

**Issue by omaralvarez** [drmohundro/SWXMLHash#36]
When I add SWXMLHash.swift to my project I get the following errors:

![Errors](http://i.imgur.com/fjCoh5B.png)

Am I doing something wrong? I'm using OSX 10.10 and targeting My Mac.

**Comment by drmohundro** [comment]
Hi @omaralvarez - are you using the version from the master branch? That version is targeting Swift 1.2 (which didn't come until Xcode 6.3). The latest Xcode release from the AppStore is actually Xcode 6.4, though I'm not sure if you can upgrade or not.

If you *can* upgrade, that would be first recommendation. If for whatever reason you can't, I'd suggest checking out some of the earlier versions. I *think* that [0.6.4](https://github.com/drmohundro/SWXMLHash/tree/0.6.4) is the most current version that works with Swift 1.1, but I'm not positive.

**Comment by omaralvarez** [comment]
Yes, you are totally right, I was using the last release of SWXMLHash and my Xcode was not updated. Upgraded to Xcode 6.4 and everything is working fine. Thanks!!
