### ISSUE TITLE
Carthage installation issue

### ISSUE THREAD

**Issue by ajsait** [drmohundro/SWXMLHash#37]
Hi,

When I tried installing SWXMLHash using Carthage, I got the following error

The following build commands failed:
	Check dependencies
(1 failure)
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.4'

Please help.

**Comment by drmohundro** [comment]
What team do you have set up for your main target? I'm just using a team of "None" in SWXMLHash. Which version of SWXMLHash are you targeting in your `Cartfile`? Also, what version of Carthage are you on? (you can see it by running `carthage version`)

**Comment by drmohundro** [comment]
I did some more research and can confirm that there appears to be an issue here - it looks like some other Swift libraries are having the same problem. Let me dig in on this some more.

**Comment by drmohundro** [comment]
Try running Carthage like so: `carthage update --configuration Debug`

**Comment by drmohundro** [comment]
Actually, nevermind, I found a code signing issue. See commit 35756609. I'll close this issue, but please comment if you still see problems. Thanks!
