### ISSUE TITLE
Module SWXMLHash has no module named parse

### ISSUE THREAD

**Issue by casoetan** [drmohundro/SWXMLHash#38]
I guess this is me not configuring this well. I'm using carthage. I've followed all the steps, but just can't use it why?

**Comment by drmohundro** [comment]
Which version of Carthage are you using? Did Carthage report any errors? Which version of Xcode are you using? Which version of SWXMLHash are you targeting in your Cartfile?

**Comment by casoetan** [comment]
I'm using version 0.75 for carthage and in targeting master in my cartfile.
Xcode version is 6.3 and no errors from carthage on build.

Thanks



Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=7.0.42&pv=5.1] On Sat, Aug 01, 2015 at 11:30 PM, David Mohundro < notifications@github.com [notifications@github.com] > wrote:
Which version of Carthage are you using? Did Carthage report any errors? Which
version of Xcode are you using? Which version of SWXMLHash are you targeting in
your Cartfile?

—
Reply to this email directly or view it on GitHub
[https://github.com/drmohundro/SWXMLHash/issues/38#issuecomment-126958586] .[https://github.com/notifications/beacon/AA_7FL00uTMMVFKe2jb6Q7h5kA_UBCZ8ks5ojUAggaJpZM4Fj8p7.gif]

**Comment by drmohundro** [comment]
It sounds like Carthage installed everything correctly - could you send the entire file that is failing over?

**Comment by casoetan** [comment]
The file
```swift
import Foundation
import SWXMLHash
import SQLite

class FileNavInteractor: NSObject {

  let xmlFile = NSBundle.mainBundle().pathForResource("file", ofType: "xml")
  let sqliteFile = NSBundle.mainBundle().pathForResource("file", ofType: "db")
  static var db: Database!

  func loadXML() {
    // Loading XML
    let xmlData = NSData(contentsOfFile: xmlFile!)
    let xmlParse = SWXMLHash.parse(xmlData) // the failing code
  }

  func loadSQLiteDB() {
    FileNavInteractor.db = Database(sqliteFile!, readonly: true)
  }
}
```

**Comment by drmohundro** [comment]
I think I'm reproducing this locally - I *think* it is related to a build setting. Do you have any build warnings in addition to the compiler errors?

**Comment by drmohundro** [comment]
Hi @casoetan - I just pushed a small change (see 35756609) which seems to resolve my local repro. If you run `carthage update` again and then try to rebuild, does it now work?

**Comment by casoetan** [comment]
Hey David,
Will try once home.
Thanks

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.3.16&pv=8.3]
On Mon, Aug 3, 2015 at 15:19, David Mohundro <notifications@github.com> wrote:
Hi @casoetan [https://github.com/casoetan] - I just pushed a small change (see 3575660
[https://github.com/drmohundro/SWXMLHash/commit/3575660933fa8d88eb54bfa03de442c4580ae8e8] ) which seems to resolve my local repro. If you run carthage update again and then try to rebuild, does it now work?

—
Reply to this email directly or view it on GitHub
[https://github.com/drmohundro/SWXMLHash/issues/38#issuecomment-127258382] .[https://github.com/notifications/beacon/AA_7FINUKqh8N8zqRRpIPUCN_UA7MT1gks5oj2_kgaJpZM4Fj8p7.gif]

**Comment by casoetan** [comment]
@drmohundro Great. It works. Now back to taking over the world.

God bless

**Comment by drmohundro** [comment]
:+1: awesome! Thanks for reporting the issue!

**Comment by nagmashade** [comment]
what is solution?

**Comment by nagmashade** [comment]
> 👍 awesome! Thanks for reporting the issue!

what is solution
