### ISSUE TITLE
SWXMLHash.parse missing some data

### ISSUE THREAD

**Issue by Huato115** [drmohundro/SWXMLHash#40]
When i put message 
responseData = &lt;div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 1&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 2&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 3&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 4&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 5&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
&lt;/div&gt;
"
let xml = SWXMLHash.parse(responseData )
and println(xml)
"
&lt;div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 1&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
  &lt;div&gt;
    &lt;div class="h"&gt;Header 2&lt;/div&gt;
    &lt;div class="b"&gt;Body&lt;/div&gt;
    &lt;div class="f"&gt;Footer&lt;/div&gt;
  &lt;/div&gt;
"

It just has only 2 childs.
Please help

**Comment by drmohundro** [comment]
Hi @Huato115 - I copied in your XML into the Swift playground that I include in SWXMLHash and it worked for me.

This is the code I used:

```swift
import SWXMLHash

let testXml = "<div>" +
"<div>" +
"<div class=\"h\">Header 1</div>" +
"<div class=\"b\">Body</div>" +
"<div class=\"f\">Footer</div>" +
"</div>" +
"<div>" +
"<div class=\"h\">Header 2</div>" +
"<div class=\"b\">Body</div>" +
"<div class=\"f\">Footer</div>" +
"</div>" +
"<div>" +
"<div class=\"h\">Header 3</div>" +
"<div class=\"b\">Body</div>" +
"<div class=\"f\">Footer</div>" +
"</div>" +
"<div>" +
"<div class=\"h\">Header 4</div>" +
"<div class=\"b\">Body</div>" +
"<div class=\"f\">Footer</div>" +
"</div>" +
"<div>" +
"<div class=\"h\">Header 5</div>" +
"<div class=\"b\">Body</div>" +
"<div class=\"f\">Footer</div>" +
"</div>" +
"</div>"

var xml = SWXMLHash.parse(testXml)

println(xml)
```

See below for the image that shows that it returned what was expected:
<img width="287" alt="screen shot 2015-08-07 at 1 13 50 pm" src="https://cloud.githubusercontent.com/assets/43072/9142601/66f7fef0-3d06-11e5-8bba-a554c3f857df.png">

Am I missing something?

**Comment by drmohundro** [comment]
I'm going to go ahead and close this one as I never heard a response back - feel free to re-open with additional comments if you feel that's necessary. Thanks!
