### ISSUE TITLE
Add Travis CI integration

### ISSUE THREAD

**Issue by drmohundro** [drmohundro/SWXMLHash#43]
I've started this by adding a `.travis.yml` file, but it isn't building yet... still working out Carthage and pulling in Quick/Nimble so that the tests can be run.

**Comment by drmohundro** [comment]
My best guess at the moment is that this related to https://github.com/Carthage/Carthage/issues/235 - per the discussion there, Carthage itself actually builds its own code signing certificate.

I checked a few other Swift libraries (AlamoFire and SwiftyJSON) to see how they're handling this and the ones I checked were all using XCTest.

**Comment by gca3020** [comment]
Any reason for not simply switching to CocoaPods? My understanding is that it has better support in TravisCI.

**Comment by drmohundro** [comment]
That's my understanding as well - to be honest, I've sort of been sitting on this because I was planning to revamp the packaging so that it could take advantage of Swift Package Manager to pull in Quick and Nimble. That probably won't be entirely feasible for a few months at least, though, as I think it is coming with Swift 3.

If I follow the lead for a few of the other top Swift libraries (Alamofire and SwiftyJSON as examples), they actually have zero dependencies as they're using the built-in testing frameworks. I've considered that, but I really like the expressiveness of Quick and Nimble. Those dependencies, though, are the only reason I couldn't get Travis going right now.

So... it is probably either hold off for SPM or switch to CocoaPods. :)

**Comment by drmohundro** [comment]
See #85, but I opted to use XCTest instead, which simplified everything (aside from the test syntax); however, this way contributors can clone and run tests right away without having to deal with any dependencies. In addition, I don't have to wait for compatible versions when new betas come out. Finally, it works on Travis now!
