### ISSUE TITLE
Help in parsing this xml format

### ISSUE THREAD

**Issue by imran20487** [drmohundro/SWXMLHash#45]
Could you please help me in parsing this format. 
I am not able to correctly parse this kind of format: I want to get the 'text' attributes value of all prop given 'child' index value.
For ex: get all prop's 'text' value given 'child' index 1
root
child index="1" name="child name 1"
prop index="1" text="prop name1" /
prop index="2" text="prop name2" /
/child
child index="2" name="child name 2"
prop index="1" text="prop name1" /
prop index="2" text="prop name2" /
/child
/root

**Comment by drmohundro** [comment]
Hey @imran20487, I noticed you closed this issue - were you able to figure this out?

**Comment by imran20487** [comment]
@drmohundro Yes, I was able to figure it out. First it was confusing for me as I was new in this xml thing. Now it is super easy to use with your library. Thanks.
Here is how I did it:
let xml = SWXMLHash.parse(data)
let childs = xml["root"]["child"].withAttr("index", "\(childID)")

let elem = childs["prop"][propID]
propName = ""
 if let attr = elem.element?.attributes
 {
    propName = attr["text"]!
 }

**Comment by drmohundro** [comment]
Great, happy you were able to get it working!
