### ISSUE TITLE
watchOS Support?

### ISSUE THREAD

**Issue by Madimo** [drmohundro/SWXMLHash#46]
> [!] The platform of the target `Watch Extension` (watchOS 2.0) is not compatible with `SWXMLHash (2.0.0)`, which does not support `watchos`.

and there is my podfile

```ruby

use_frameworks!
inhibit_all_warnings!

target 'MyMainAppTarget' do
    platform :ios, '8.0'

    ...
end

target 'MyWatchExtensionTarget' do
    platform :watchos, '2.0'

    pod 'SWXMLHash'
end

```

**Comment by drmohundro** [comment]
Hey @Madimo, thanks for the report! I'll see if I can get watchOS support - hopefully it's just a matter of adding a new target to the build.

**Comment by leoMehlig** [comment]
I think all it takes is to add:

 s.watchos.deployment_target = '2.0'

to the podspec.

**Comment by drmohundro** [comment]
Thanks for the tip @leoMehlig - I think you're right. I just published the 2.0.1 version of SWXMLHash with the modifications. @Madimo can you try out 2.0.1 to see if that works for you?

**Comment by Madimo** [comment]
Yes it works. Thanks! @drmohundro

**Comment by drmohundro** [comment]
Great!
