### ISSUE TITLE
Carthage built framework doesn't contain SWXMLHash.swift file

### ISSUE THREAD

**Issue by chrisamanse** [drmohundro/SWXMLHash#47]
The Carthage built framework doesn't contain the `SWXMLHash.swift` file, thus, I can't jump to definition using Xcode.

**Comment by drmohundro** [comment]
Is that even possible with Carthage? Carthage builds framework binaries that you then integrate into your project. It does pull the code down so that it can build the binary, but I'm not aware of supporting a means of jumping to definition with it.

If I'm incorrect, though, please let me know!

**Comment by chrisamanse** [comment]
Oh, ok, my bad. You're right, I verified it on other Carthage compatible libraries, and jump to definition does not really work.

**Comment by drmohundro** [comment]
:+1: Cool... I didn't think so, but wasn't sure. I'll close this issue then. Thanks!
