### ISSUE TITLE
Printing 'nil' for every value I try to retrieve

### ISSUE THREAD

**Issue by ivanalvarado** [drmohundro/SWXMLHash#49]
Hello,

I'm trying to get SWXMLHash working with my project. I have the URL of an XML file. When I try to retrieve the 'text' of certain elements, as well as attributes, I keep getting 'nil'. I must be doing something wrong, but I don't know what.

I've installed SWXMLHash via CocoaPods. 

A sample of what the XML file looks like is,

```XML
<coord2 count="9">
  <markers>
    <marker>
      <lat>36.97734</lat>
      <lng>-122.05444</lng>
      <timestamp>1445016544</timestamp>
      <route>LOOP</route>
      <id>7855</id>
      <predictions>
      ,8,9,,10,11,,,,14,,,15,,15,,17,1,,0,,,3,,,4,,,6,,,,,,,,,,,,,,
      </predictions>
      <update_seconds>10</update_seconds>
      <index>0</index>
    </marker>
    <marker>
      <lat>36.97772667</lat>
      <lng>-122.053615</lng>
      <timestamp>1445016539</timestamp>
      <route>LOOP</route>
      <id>7860</id>
      <predictions>
      9,,,8,,,7,6,5,,4,3,,2,,1,,,0,,15,14,,13,12,,11,10,,,,,,,,,,,,,,,
      </predictions>
      <update_seconds>10</update_seconds>
      <index>0</index>
    </marker>
  </markers>
  <curr_time>1445016544</curr_time>
</coord2>
```

The following is what my code looks like,

```Swift
import UIKit
import SWXMLHash

class ViewController: UIViewController {

    override func viewDidLoad() {
        super.viewDidLoad()
        // Do any additional setup after loading the view, typically from a nib.
        
        let xml = SWXMLHash.config {
            config in
            config.shouldProcessNamespaces = true
            }.parse("http://url.to.xmlfile.xml")
        
        print(xml["coord2"].element?.attributes["count"])
        print(xml["coord2"]["markers"]["marker"][0]["lat"].element?.text)
    }

    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
}
```

I'm expecting my program to output:
**9**
**36.97734**

but I'm getting:
**nil**
**nil**

I am running Xcode v 7.0.1 (Swift 2.0 I think).

Thank you for your help!

**Comment by drmohundro** [comment]
It looks like the problem is that you're passing a URL to `parse` instead of a string containing XML or NSData referencing XML. SWXMLHash doesn't actually do anything to download a string - it thinks the string you're passing is XML so it is trying to find "coord2" in the string "http://url.to.xmlfile.xml".

For this situation, you'll probably want to use something like `NSMutableURLRequest` to download the content from the URL and *then* pass the downloaded string into SWXMLHash.

Hope that makes sense.

**Comment by drmohundro** [comment]
I'm going to go ahead and close this one as I haven't heard any response... please comment back if there are further issues, though. Thanks!

**Comment by dan1eln1el5en** [comment]
had the same problem, and indeed it was the NSData missing (I had only pointed at the file location (in a bundle)
perhaps it's a newbie mistake, or maybe it's worth to add a note about in the documentation.
