### ISSUE TITLE
iOS9?

### ISSUE THREAD

**Issue by jshultz** [drmohundro/SWXMLHash#53]
i see that it's targetting iOS8. will this work on iOS9 as well?

I'm running swift 2 and ios9, just curious if this is will work or not?

**Comment by drmohundro** [comment]
Yup, it works fine - iOS 8 is the minimum required version (at least if you want to use CocoaPods or Carthage). I know a few people are even targetting iOS 7 by dropping the source directly in their project.

**Comment by jshultz** [comment]
Sweet, so I could just change it to this: `platform :ios, '9.0'` and be golden? 

I'm assuming so. :)

**Comment by jshultz** [comment]
When I do the pod install I get the following message:

`Downloading dependencies
Installing SWXMLHash (2.0.2)
[!] Pods written in Swift can only be integrated as frameworks; this feature is still in beta. Add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: SWXMLHash`

**Comment by jshultz** [comment]
So, I got the pod to install, I just did like it said and added use_frameworks! to the podfile.

It seems to be installed, but when I try to import the file into my view controller i'm getting `no such module "SWXMLHash"` ?

I added `$(SRCROOT)` to the Framework Search Paths but that doesn't seem to make a difference?

**Comment by drmohundro** [comment]
I just tested it out with a brand new iOS project and it all worked.

Here's my `Podfile`:

```
platform :ios, '9.0'

use_frameworks!

pod 'SWXMLHash'
```

One thing, make sure you open the newly created workspace file (`Foo.xcworkspace`) as opposed to the xcodeproj (`Foo.xcodeproj`).

Also, it might give you that error until you fully compile.

**Comment by jshultz** [comment]
That was the problem. I was opening the wrong file. Thanks!

**Comment by drmohundro** [comment]
Awesome, glad it is working now!
