### ISSUE TITLE
tvOS target?

### ISSUE THREAD

**Issue by dhmspector** [drmohundro/SWXMLHash#54]
Hi 

Would it be possible to get a tvOS target? (I've forked a copy and added the new target for tvOS, and it seems to compiles fine, and even builds a framework but I couldn't get Carthage to see the tvOS scheme...  I'll be happy to issue a PR for my (utterly trivial) changes but might be faster for you to just add the target).

best,
David

**Comment by drmohundro** [comment]
Yeah, I'd be happy to - I'll try to get around to it some time tomorrow. I had already added tvOS and watchOS support with CocoaPods, but I had forgotten to add an actual target in the project itself.

**Comment by dhmspector** [comment]
Awesome - thanks! (btw, is there a trick to getting Carthage to pick up all the build targets? I matter what I tried I couldn't get it to see the SWXMLHashtvOS target I'd added to my copy, and the Carthage docs didn't offer any useful clues..)

best,
 Dave

**Comment by drmohundro** [comment]
It took me a little longer than expected, but it should be out there now. I added a `watchOS` target, too.

**Comment by dhmspector** [comment]
Thank you very much!  And, by the way, thank you very much for creating such a great utility - it's saving me a lot of time grinding through really large and complex XML files that would have otherwise eaten up a lot of dev time to handle with NSXMLParser.

best,
 Dave

**Comment by drmohundro** [comment]
I'm happy it is helping out - working with NSXMLParser can be a pain!
