### ISSUE TITLE
tvOS target has no sources to compile :\

### ISSUE THREAD

**Issue by dhmspector** [drmohundro/SWXMLHash#56]
Hi David,

Just got around to adding the tvOS framework to my project (spent the last week writing an importer to capture data which was mostly under OS X) and noticed I was getting an error in the editor when I tried to write 

let xml = SWXMLHash.parse(data!)

that there was no parse method on the object when using the framework in the tvOS branch. I'd been using it all week in iOS and OS X so that was a little confusing :|   ...turns out the swift file isn't in the build list for tvOS:

![screen shot 2015-11-20 at 3 43 45 pm](https://cloud.githubusercontent.com/assets/21057/11314791/e634eaae-8f9d-11e5-9eca-65b9fe6642f7.png)

(just did a fresh pull, just to check, and it's the same on the master branch)

**Comment by drmohundro** [comment]
And... that's probably what I get for doing my fix late at night.

Sorry about that - I'll get that fixed.

**Comment by drmohundro** [comment]
Well that was dumb of me. It is fixed as of `2.0.5`.
