### ISSUE TITLE
Getting Attribute count to add values to an array in Swift with SWXMLHash

### ISSUE THREAD

**Issue by zdigitalpro** [drmohundro/SWXMLHash#59]
Here is the XML I'm parsing with SWXMLHash:

```xml
<response version="1.2" xsi:noNamespaceSchemaLocation="http://aviationweather.gov/adds/schema/metar1_2.xsd" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XML-Schema-instance">'
	<request_index>7394484</request_index>
	<data_source name="metars"/>
	<request type="retrieve"/>
	<errors/>
	<warnings/>
	<time_taken_ms>4</time_taken_ms>
	<data num_results="1">
		<METAR>
			<raw_text>KDEN 261153Z 07012KT 3SM -FZDZSN BKN004 OVC008 M05/M06 A3009 RMK AO2 SLP213 P0000 60000 I1000 I6000 T10501061 11039 21050 53009</raw_text>
			<station_id>KDEN</station_id>
			<observation_time>2015-11-26T11:53:00Z</observation_time>
			<latitude>39.85</latitude>
			<longitude>-104.65</longitude>
			<temp_c>-5.0</temp_c>
			<dewpoint_c>-6.1</dewpoint_c>
			<wind_dir_degrees>70</wind_dir_degrees>
			<wind_speed_kt>12</wind_speed_kt>
			<visibility_statute_mi>3.0</visibility_statute_mi>
			<altim_in_hg>30.088583</altim_in_hg>
			<sea_level_pressure_mb>1021.3</sea_level_pressure_mb>
			<quality_control_flags>
				<auto_station>TRUE</auto_station>
			</quality_control_flags>
			<wx_string>-FZDZ SN</wx_string>
			<sky_condition cloud_base_ft_agl="400" sky_cover="BKN"/>
			<sky_condition cloud_base_ft_agl="800" sky_cover="OVC"/>
			<flight_category>LIFR</flight_category>
			<three_hr_pressure_tendency_mb>0.9</three_hr_pressure_tendency_mb>
			<maxT_c>-3.9</maxT_c>
			<minT_c>-5.0</minT_c>
			<precip_in>0.005</precip_in>
			<metar_type>SPECI</metar_type>
			<elevation_m>1640.0</elevation_m>
		</METAR>
	</data>
</response> 
```

I want to get the count of sky_condition sky_cover sky_base_ft_agl as there is always at least one with no cloud base (CLR) or multiple FEW, BKN or OVC with cloud bases with each.  I want to be able to get the number of sky conditions and then enumerate through them and add them to an array so that I can show them on a  label together.

Here is the code I have to get the data to parse and then present to a label:

```swift
 func getWxData () {
        
        let urlStringMax = "https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=3&mostRecent=true&stationString=KDEN"
        
    if let urlMax = NSURL(string: urlStringMax) {
        
        if let data = try? NSData(contentsOfURL: urlMax, options: []) {
        
           let xml = SWXMLHash.parse(data)
           print(xml)
            
            metar1 = xml["response"]["data"]["METAR"]["raw_text"].element!.text!
           skycover = xml["response"]["data"]["METAR"]["sky_condition"][0].element?.attributes["sky_cover"]
         print(skycover)
            
            }
        }
    }
```

Any help would be greatly appreciated!!

**Comment by drmohundro** [comment]
Quick request @zdigitalpro - could you edit your question to wrap the XML in code (i.e. \`\`\` at top and bottom)? It looks like the tags were stripped so I can't tell anything about the tag structure. Thanks!

**Comment by zdigitalpro** [comment]
Sorry, just updated so that it represents the XML properly.  Thanks!!

**Comment by zdigitalpro** [comment]
Just fixed it, sorry!  I really appreciate you taking the time to help!  I really like SWXMLHash.  Just need to get the syntax correct. 

Jim

**Comment by zdigitalpro** [comment]
Ok, updated the post so that you can see the code.  My previous comment indicated I fixed it, I have not fixed the parser question.  I just fixed the post so that you could see the xml.  Thanks!

**Comment by zdigitalpro** [comment]
Getting there - I got the count this way:
let skyCount = xml["response"]["data"]["METAR"]["sky_condition"].all.count
Now I just need to enumerate through and put them in an array.

**Comment by drmohundro** [comment]
The `children` method is how you can enumerate all children of an element - can you try that?

**Comment by zdigitalpro** [comment]
Ok, I will give it a go!  I will let you if I can get it to work.  Thanks!

**Comment by zdigitalpro** [comment]
I can get the element names listed using the children method.  If there is more than one sky_condition, i.e, FEW, BRK, OVC, etc. I get multiple 'sky_conditions".  If I use Attributes instead of children, I get the child plus the value, but with all the extra characters.  I'm on the right track, just need some pointers, still learning!!

**Comment by zdigitalpro** [comment]
Below is what I finally came up with.  Any comments would be appreciated.  I don't have all the weather elements, just a basic start of how I am proceeding.

 func getWxData () {
        
        let urlStringMax = "https://www.aviationweather.gov/adds/dataserver_current/httpparam?dataSource=metars&requestType=retrieve&format=xml&hoursBeforeNow=3&mostRecent=true&stationString=" + (airport) as String
        
    if let urlMax = NSURL(string: urlStringMax) {
        
        if let data = try? NSData(contentsOfURL: urlMax, options: []) {
        
           let xml = SWXMLHash.parse(data)
            
            metar1 = xml["response"]["data"]["METAR"]["raw_text"].element!.text!
            skyCount = xml["response"]["data"]["METAR"]["sky_condition"].all.count
            
            for (var i = 0; i < skyCount ; i++) {
            skyArray.addObject(xml["response"]["data"]["METAR"]["sky_condition"][i].element!.attributes["sky_cover"]! + " " + xml["response"]["data"]["METAR"]["sky_condition"][i].element!.attributes["cloud_base_ft_agl"]!)
                
            }
        
            }
        }
    }

**Comment by drmohundro** [comment]
I'm not entirely sure what the XML looks like when there are multiple elements - I would *guess* that there would be multiple `METAR` elements.

Assuming that is the case, your code could do something like this:

``` swift
let xml = SWXMLHash.parse(data)

for metarElem in xml["response"]["data"]["METAR"] {
	for skyCondition in metarElem["sky_condition"] {
		skyConditionArr.addObject("sky condition attr \(skyCondition.element?.attributes["sky_cover"])")
	}
}
```

It sounds like the handling will vary depending on the type of `sky_cover` so you'd have to handle that of course.

I've had lots of family in town for the past few days and into the weekend, so I haven't had a chance to double check this code but an approach something like that *should* work.

**Comment by zdigitalpro** [comment]
Ok, I will try it out and let you know, again, thanks for taking the time to help!

**Comment by zdigitalpro** [comment]
I modified what you suggested code and below it prints out the information I need.  I combined the Sky Condition and Cloud base as they should be printed together.  Thanks for all your help!!

**Comment by drmohundro** [comment]
Great, glad you were able to get it working!
