### ISSUE TITLE
watchOS build doesn't actually include the source file

### ISSUE THREAD

**Issue by alwaysthecritic** [drmohundro/SWXMLHash#60]
I was banging my head against this for a couple of hours, getting an error "Module SWXMLHash has no member named ‘parse" in my WatchKit extension code. It turned out that the SWXMLHash WatchOS target doesn't actually include the single SWXMLHash.swift source file in its WatchOS target, so indeed, the framework really didn't have a member named parse.

I fixed this locally by selecting the project to see build settings, selecting the WatchOS target, then Build Phases > Compile Sources, then dragged SWXMLHash.swift into the empty list of source files.

I'd submit a pull request to fix this, but given it's project settings, it's probably easier for all concerned for you (the author) to make the change directly, though I can submit a PR if you prefer.

**Comment by drmohundro** [comment]
Hmm... I've got them in master at least. See screenshot:

![2015-12-30_17-20-44](https://cloud.githubusercontent.com/assets/43072/12059068/ac9e04ce-af19-11e5-972b-ab9f73a5e83e.png)

How are you referencing the project? CocoaPods, Carthage or straight from source? I'm wondering if I may need to publish a new podspec if you're using CocoaPods.

(as an aside, I'm clearly terrible with project settings - see #56 as an example... sigh)

**Comment by alwaysthecritic** [comment]
I'm using Carthage. My Cartfile says:
github "drmohundro/SWXMLHash" ~> 2.0

Cartfile.resolved is:
github "drmohundro/SWXMLHash" "2.0.5"

**Comment by drmohundro** [comment]
Ah, I see - I didn't tag the commits after `2.0.5`. I just pushed `2.0.6` which includes the everything in master. See if that fixes your issue. Sorry for the hassle and thanks for reporting it!

**Comment by alwaysthecritic** [comment]
Great - all works now. Thanks.
