### ISSUE TITLE
Parsing question

### ISSUE THREAD

**Issue by acegreen** [drmohundro/SWXMLHash#63]
First off, many thanks for this library and great work

I managed to get the rss xml parsed and it looks like this 

```
<rss version="2.0">
     <channel>
        <title>
       </title>
        <title>
       </title>
         .......
     </channel>
</rss>
```

So I'm trying to extract the title as such but its not returning anything. 

            for elem in xml["rss version=\"2.0\""]["channel"] {
                
                print(elem["title"].element!.text!)
            }

**Comment by acegreen** [comment]
Ah it should be 

```
for elem in xml["rss"]["channel"] {
            print(elem["title"].element!.text!)
 }
```

**Comment by drmohundro** [comment]
Hi @acegreen - glad you were able to figure it out! Yup, the `version` part of the `rss` element is the attribute - there is support for filtering elements by attribute as well, but it looks like you don't need that at the moment.
