### ISSUE TITLE
I'm unable to use the framework in the playground 

### ISSUE THREAD

**Issue by aziz-boudi4** [drmohundro/SWXMLHash#69]
The framework is working fine in my project, but I'm unable to import the framework in the playground.

I keep having this output in the console: 
`Playground execution failed: bart-Sample-playground.playground:4:8: error: no such module 'SWXMLHash'`

`import SWXMLHash`
           `^`
- I tried to delete the content of the derived data folder.
- I also tried to clean and build.

How can I use the framework inside a playground ?

**Comment by drmohundro** [comment]
I saw you [asked about this](http://stackoverflow.com/questions/36166238/how-can-i-use-a-third-party-library-swxmlhash-in-the-playground) on StackOverflow - were you able to make any progress with that approach?

There are also docs here - https://developer.apple.com/library/ios/recipes/Playground_Help/Chapters/ImportFramework.html.

**Comment by aziz-boudi4** [comment]
Thanks for your reply, No I'm still unable to run the framework inside the playground.
It was working when I deleted the content of the "derived data folder" in xcode, but this solution doesn't work anymore

**Comment by aziz-boudi4** [comment]
I followed the steps that are provided in the docs that you posted, and it worked.
Thank you, I'm able to run the framework SWXMLHash in my playground.

**Comment by drmohundro** [comment]
Awesome, glad that link worked!

**Comment by aziz-boudi4** [comment]
It's very strange, it worked well for a couple of days and now it stopped again saying 
`cannot load underlying module for 'SWXMLHash'`
