### ISSUE TITLE
Allow easy enumeration of child elements.

### ISSUE THREAD

**Issue by drmohundro** [drmohundro/SWXMLHash#7]
I *thought* that `.all` would allow for easy enumeration of child elements (such as when the XML is dynamic), but it doesn't appear to work.

The API I have in mind is something like:

```swift
func enumerate(xml: XMLIndexer) {
    for elem in xml.all {
        enumerate(elem)
    }
}

enumerate(xml)
```

**Comment by AllenConquest** [comment]
I'd like to be able to use this library to display an XML document in a tableView control. Indicate whether there are children and then drill down into those using a nested tableview when selecting a row

**Comment by drmohundro** [comment]
@AllenConquest I just pushed some changes to add a new property called `children` which lists all child elements from the current element. I've updated the docs to denote this as well.

Take a look and see what you think. It doesn't do anything to automatically plug into a table view control, but you should be able to take this to then populate a table view control.

Let me know if you have any questions.
