### ISSUE TITLE
Add support for automatic deserialization of Bool types

### ISSUE THREAD

**Issue by gca3020** [drmohundro/SWXMLHash#70]
The automatic type conversion in https://github.com/drmohundro/SWXMLHash/pull/68 lacks support for Bool types. The W3C specification defines a boolean as follows:

> 3.2.2.1 Lexical representation
> 
> An instance of a datatype that is defined as ·boolean· can have the following legal literals {true, false, 1, 0}.

SWXMLHash should support automatic decoding of at least these four values into Swift Bool primitives.

**Comment by drmohundro** [comment]
Thanks for opening this issue - feel free to comment or shoot me an email if you'd like help with the PR flow, etc.

**Comment by drmohundro** [comment]
`2.3.0` is out!
