### ISSUE TITLE
Add automatic deserialization of attributes.

### ISSUE THREAD

**Issue by gca3020** [drmohundro/SWXMLHash#74]
Recent pull request #68 from @ncreated introduced automatic type conversion for Elements and Indexers, but working with attributes is still painful. I am working with some (imo) poorly designed XML, which has a number of elements like this:

`<stats minplayers="2" maxplayers="2" minplaytime="40" maxplaytime="60" playingtime="60" numowned="253" rating="8.5">`

It would be nice to be able to automatically convert these attributes into Int, Float, Double, Bool, and String types (as well as Int?, Float?, etc...) with a syntax similar to `node["test"].value()`.

As it stands now, when processing attributes within a deserializer, I need to do crazy optional gymnastics, like this:
```
var minPlayers: Int
if let minPlayersString = node["stats"].attribute("minplayers") {
   if let minPlayersInt = Int(minPlayersString) {
      minPlayers = minPlayersInt
   }
}
```

I would love to be able to replace this with something like this:
var minPlayers: Int = node["stats"].attribute("minplayers")

Swift's 'guard' syntax makes this slightly less laborious if the values are guaranteed to be there, but there is still certainly room for improvement.

**Comment by drmohundro** [comment]
Good idea, I like it. In fact, I suspect that most attributes would be serializable with little to no effort because there won't be any hierarchy in them.

At the moment, attributes are just simple `[String:String]()` dictionaries. I *lean* towards wrapping the actual value in a new struct and then hanging a `value()` call of it for deserialization. That way, the deserialization isn't hanging off of `String`.

I'll see if I can find some time and get this added.

**Comment by drmohundro** [comment]
Just thought of something, one caveat with changing the type of `attributes` is that it could be a breaking change. I'd really like to avoid any API changes... I'll play with it and see, though.

**Comment by drmohundro** [comment]
Yeah, providing a new `attribute` method instead of just an `attributes` dictionary could work and that would be backwards compatible... it'd be odd from a discoverability perspective as there would be both an `attribute` and an `attributes` hanging off of an element. Maybe if it were named `findAttribute`? Then the `attributes` property is just all of them, but there is a built-in way to get at a specific one.

As far as generics go, I hear ya - most of my generics experience actually comes from C#. It is more similar to Swift than templates in C++, but they're still different. I guess we're all learning it!

I'm open to suggestions regarding good names, though.

**Comment by gca3020** [comment]
Looking at the [Swift API Design Guidelines](https://swift.org/documentation/api-design-guidelines/), the "Swiftiest" way would probably be `element.get(attribute: "someattribute")` or something similar.

**Comment by drmohundro** [comment]
I've been thinking about this... I'm not sure `get` makes sense because based on the [name translation for Swift 3.0](https://github.com/apple/swift-evolution/blob/master/proposals/0005-objective-c-name-translation.md), it mentions to "Never transform a name into 'get', 'set', 'with', 'for', or 'using'" when translating from Objective-C names to Swift names.

Given that and the guidance in [Apply API Guidelines to the Standard Library](https://github.com/apple/swift-evolution/blob/master/proposals/0006-apply-api-guidelines-to-the-standard-library.md), I think it should be something like this:

```swift
func attributes(by name:String) -> String {
}
```

**Comment by drmohundro** [comment]
@gca3020 if you get a chance, could you check out PR #81? It's my first attempt at setting this up. I added a new `XMLAttribute` type that has a `value()` method on it that follows the same basic approach that the element serialization uses (mainly for consistency).

Let me know your thoughts. (I also deprecated the `attributes` property, too).

**Comment by gca3020** [comment]
At first glance it looks like it will work nicely. I'll take a look either a little later in the week or next weekend. This weekend is a little busy for me because of the holiday. Thanks!

**Comment by drmohundro** [comment]
No rush, take your time! It did take me 2 months to actually get something after all! I just want to make sure it fits a use case other than what I'm envisioning :)

**Comment by gca3020** [comment]
I finally got a chance to look at this, and it's nearly what I had envisioned, but I think it's not quite there yet, and missing one little thing to make it more usable. My biggest problem is that the current method requires a lot of Swift Optional hurdles, which make the code necessarily more verbose than I would like. I am working on some slight modifications, but here's what I am envisioning:

Adding similar `.value<T: XMLAttributeDeserializable>(ofAttribute: String)` methods to XMLIndexer as already exist for elements, which will handle the unwrapping and "array-izing" of the attributes. This would have the end result of allowing syntax like `node["foo"].value(ofAttribute: "bar")` rather than the more verbose `node["foo"].element!.attribute(by: "bar")!.value()` while also remaining safer. 

It will throw a Swift Error on a problem rather than crash with a fatal error trying to unwrap an optional, without the API user having to write a bunch of `guard let` statements. It also lets you get collections of attribute values, and in general allows accessing of attribute text exactly as if it was element text.

If you agree, I will start making the changes, and hopefully submit a pull request later this week.

**Comment by drmohundro** [comment]
Interesting thought - I hadn't considered actually using the existing `value()` method but with an `ofAttribute` parameter. I think I like that.

And regarding your comments regarding how verbose all of the unwrapping is, I do agree there - it is pretty obnoxious at the moment. My personal thinking is that I'd like to keep the `XMLElement` and `XMLAttribute` classes for the internal modeling of the XML content while possibly changing them to be enums. However, they could be implementation details at that point and then `XMLIndexer` would be the sole public API for the library which would clean up all of the unwrapping stuff.

Does that line up with your thoughts here (and also regarding version 3)?

If you'd like to put a pull request to #81 (or create a new one), that's fine with me. Thanks again for your input - it is very helpful!

**Comment by gca3020** [comment]
I just posted a Pull Request that implements the behavior I mentioned, as well as merging the XMLAttribute work you have already done onto master (pulling with it the XCTest changes).

I wasn't sure if it was better to create a new PR or to push an addition to #81, but I decided since I was also doing some merging to master, it would be easier to create a new one.

There are still some SwiftLint issues, but they were all there before I started, and I didn't know how you would want them fixed, so I picked off some low-hanging fruit.

Let me know if you have any comments or would like me to make any changes.

**Comment by drmohundro** [comment]
Awesome, this looks great - it is merged and I just published `2.5.0` with these changes. I'll also see about getting this merged into the Swift 3 branch.

**Comment by drmohundro** [comment]
And... this is now in the Swift 3 branch, too.

**Comment by estemendoza** [comment]
Thanks for this guys, I think it's a better design.

Now, because I am still new in Swift, I have a question. Now, to get the value of an attribute, I am doing the following:

`(item.element!.attribute(by: "id")?.text)!`

Is this correct? there isn't a simpler way to do this? I am working with Xocde 8 and Swift 3.

Thanks

**Comment by gca3020** [comment]
That will work, yes, but an (in my opinion) better way to get at the attributes is (assuming `item` is an `XMLIndexer`) as follows:

`idString = item.value(ofAttribute: "id")`

As long as idString is declared to be of type string, the type will be inferred, and you don't have to do any casting. Other Swift-isms like this should work too:

`var idString = item.value(ofAttribute: "id") as String`

Similarly, if your attribute is an integer, double, float, or bool, it should automatically convert to that type, assuming the variable you're assigning to is a double, float, or bool.

**Comment by estemendoza** [comment]
Thank you so much for this, I will try it.

One final thing. The best way to check if an attribute exists is the following?

`if let attr = item.element!.attribute(by: "id")`

**Comment by estemendoza** [comment]
By the way, I am looping in the xml in the following way:

```
for item in parser["events"].children{
    let test = (item.element!.attribute(by: "id")?.text)!
}
```

And I tried what you suggested, but it seems it is not an `XMLIndexer`, right?

**Comment by gca3020** [comment]
I'm not in front of my mac, but I would guess it would be something more like this:

`for item in parser["events"].children {
   if let test = (item.value(ofAttribute: "id) as String?) {
      // do a thing
   } else {
      // do a different thing
   }
}`

As a general rule, I try to avoid forced unwrapping (the `!` operator) as much as possible, especially when parsing input that might not be properly formed.

**Comment by estemendoza** [comment]
I don't know why, but it keeps telling me that "value" is not a valid member of `XMLIndexer`

**Comment by gca3020** [comment]
What version are you running?

**Comment by estemendoza** [comment]
One that I shouldn't be using, really sorry! I should be using this one, right? https://github.com/drmohundro/SWXMLHash/tree/xcode-8.0/Source

**Comment by gca3020** [comment]
If you're running Swift3/XCode8, yes. Otherwise, you want the 2.5.1 tag.

**Comment by estemendoza** [comment]
Yeah, I am using that version now and still doesn't work! It's driving me crazy. It seems that it doesn't realize that there is an extension for XMLIndexer (it's in a different file now, SWXMLHash+TypeConversion.swift)

**Comment by gca3020** [comment]
Sounds like you have some build issues. I would encourage you to check out the Playground, and see if it works in there, or if you are integrating it into your own project/workspace, follow the Carthage and/or CocoaPods directions in the README.

**Comment by estemendoza** [comment]
Ok, there is something weird here. I am doing different tests with the playground and while executing this:
```
// custom types conversion
let booksXML = "<root id='12345'>" +
"  <books>" +
"    <book>" +
"      <title>Book A</title>" +
"      <price>12.5</price>" +
"      <year>2015</year>" +
"    </book>" +
"    <book>" +
"      <title>Book B</title>" +
"      <price>10</price>" +
"      <year>1988</year>" +
"    </book>" +
"    <book>" +
"      <title>Book C</title>" +
"      <price>8.33</price>" +
"      <year>1990</year>" +
"      <amount>10</amount>" +
"    </book>" +
"  <books>" +
"</root>"

xml = SWXMLHash.parse(booksXML)

let books: [Book] = try xml["root"]["books"]["book"].value()

for prod in xml.children{
    prod.value(ofAttribute: "id")
}
```

I get this:

```
Playground execution failed: error: SWXMLHashPlayground.playground:90:5: error: ambiguous reference to member 'value(ofAttribute:)'
    prod.value(ofAttribute: "id")
    ^~~~
```

Why is that?

**Comment by gca3020** [comment]
My guess is you have to assign it to a variable. What you have now is basically 
```
for something in something {
   7
}
```

If you'd like, feel free to message me directly, so we don't keep cluttering up this closed issue, notifying everyone who is subscribed.

**Comment by estemendoza** [comment]
Yeah, seems better. How do I contact you?

**Comment by drmohundro** [comment]
@estemendoza so is it working for you now? You mentioned contacting someone - if you're still needing help, I'd recommend either posting a new issue, submitting a question on StackOverflow, or if you'd like, you can shoot me an email and I can try to help out when I have some time to look.

**Comment by estemendoza** [comment]
Well, sorry for all the notifications. I decided to make a question here because I think it involves the changes made on this ticket.

No, this still doesn't work for me, I am having the last problem that I said to @gca3020 which is the following:

`Ambiguous reference to member 'value(ofAttribute:)'`

when I try to do something like this

`let test = item.value(ofAttribute: "id")`

Check my code a few messages above to try it on the Playground

**Comment by gca3020** [comment]
No problem. I'm happy to help. With the question above, since value(ofAttribute) makes use of Swift Generics, for the type inference to work, 'test' needs to have a type specified. 

in the example above, you could either declare test as a var, and give it a type (e.g. `var test: String`) before you assign to it, or explicitly tell the compiler that what you're trying to do is call value() and put the result in a `String` (or `String?`) with the `as String?` directive.

`let test = (item.value(ofAttribute: "id") as String?)`

Twitter is the best way to contact me, or gmail (both at the same username).

**Comment by estemendoza** [comment]
It's working now! I wasn't understanding that last comment. Thank you so much for your patience and I won't bother anymore around here. Any other question I will contact you directly. Thanks again!

**Comment by gca3020** [comment]
Glad you got it working. Note that the really cool part of the deserialization is that you can use the 'as' directive to treat it as more than just a string. If you think the attribute contents are really an integer or double, just use `as Double?` instead, and it will handle all of the typecasting in a safe way for you. 

Alternately, if you're really sure with your particular xml that the attribute really should be there, you can do `as Double` (without the `?`) and it will throw a Swift Error (exception) if it is not, which you can catch and handle appropriately.
