### ISSUE TITLE
Deserializing a single element into an array

### ISSUE THREAD

**Issue by joeltrew** [drmohundro/SWXMLHash#76]
Hi there, I'm wondering if its possible to deserialize a single XML element into an array.

For example with the given xml
`<distances>1,2,3,4,5,6,7</distances>`

Is it possible to deserialize into [Int] ?

Thanks!

**Comment by joeltrew** [comment]
I ended up extending XMLIndexer with a function `deserializeStringPartsToArray<T: StringInitializable>(seperator: String) -> [T]? ` which I use in place of `.value()`

**Comment by drmohundro** [comment]
Okay, for something like that to work, you'd actually have to write your own deserialization support (see https://github.com/drmohundro/SWXMLHash/blob/master/Tests/SWXMLHashSpecs.swift#L804-819) as an example as the library today doesn't support deserializing a single element to an array (though it does support multiple elements to an array).

If you opted to do that (versus your current solution), you'd likely have something like:

```swift
struct SingleElementToArray: XMLIndexerDeserializable {
    let values: [Int]

    static func deserialize(node: XMLIndexer) throws -> ComplexItem {
        return try SingleElementToArray(
            values: node["distances"].value().componentsSeparatedByString(",")
        )
    }
}
```

Big disclaimer that I haven't verified the above code 😄 

Hope this helps!

**Comment by joeltrew** [comment]
Thanks that's a nice way of solving the issue! Thanks for your work on this framework by the way, its really well done. I've learnt a lot reading through the source code as well 😁

**Comment by drmohundro** [comment]
That's great to hear - I'm glad the code has been helpful/useful!
