### ISSUE TITLE
Incomplete XML

### ISSUE THREAD

**Issue by GabrielAraujo** [drmohundro/SWXMLHash#77]
Hello,

I have the bellow code:

let xml = SWXMLHash.parse(data!)

let servResponse = xml["response"]["sucesso"].element?.text == "true" ? true : false

if servResponse == true {

          let resData = xml["response"]

           for obj in resData["XMLGridData"] {

            ...

           }
}

The XML that I'm looping is huge and contains 200 tags of "XMLGridData"..

But when I do the SWXMLHash.parse(data!) from the Alamofire it only iterates with 10 tags of "XMLGridData".

See the Xml limited
`<response>
    <sucesso>true</sucesso>
    <retorno>Consulta Realizada Com Sucesso!</retorno>
    <XMLGridData>
        <Bike_Sq>2</Bike_Sq>
        <Bk_Bike_ID>1</Bk_Bike_ID>
        <PT_agency_id>1</PT_agency_id>
        <PT_agency_name>Bikesampa</PT_agency_name>
        <Bk_PL_ID>2</Bk_PL_ID>
        <Bk_Total>12</Bk_Total>
        <Bk_Available>1</Bk_Available>
        <Bk_Last_UPDATE>2016-05-15T19:00:00</Bk_Last_UPDATE>
        <Bk_Active>1</Bk_Active>
        <PL_LT>-2.358731500000000e+001</PL_LT>
        <PL_LG>-4.664797400000000e+001</PL_LG>
        <PL_Desc>BikeSampa -Instituto Biologico</PL_Desc>
    </XMLGridData>
    <XMLGridData>
        <Bike_Sq>3</Bike_Sq>
        <Bk_Bike_ID>2</Bk_Bike_ID>
        <PT_agency_id>1</PT_agency_id>
        <PT_agency_name>Bikesampa</PT_agency_name>
        <Bk_PL_ID>3</Bk_PL_ID>
        <Bk_Total>14</Bk_Total>
        <Bk_Available>0</Bk_Available>
        <Bk_Last_UPDATE>2016-05-15T19:00:00</Bk_Last_UPDATE>
        <Bk_Active>1</Bk_Active>
        <PL_LT>-2.359222700000000e+001</PL_LT>
        <PL_LG>-4.664684400000000e+001</PL_LG>
        <PL_Desc>BikeSampa -Cinemateca</PL_Desc>
    </XMLGridData>
    <XMLGridData>
        <Bike_Sq>4</Bike_Sq>
        <Bk_Bike_ID>3</Bk_Bike_ID>
        <PT_agency_id>1</PT_agency_id>
        <PT_agency_name>Bikesampa</PT_agency_name>
        <Bk_PL_ID>4</Bk_PL_ID>
        <Bk_Total>12</Bk_Total>
        <Bk_Available>1</Bk_Available>
        <Bk_Last_UPDATE>2016-05-15T19:00:00</Bk_Last_UPDATE>
        <Bk_Active>1</Bk_Active>
        <PL_LT>-2.359309900000000e+001</PL_LT>
        <PL_LG>-4.664239800000000e+001</PL_LG>
        <PL_Desc>BikeSampa -Capitao Macedo</PL_Desc>
    </XMLGridData>
    <XMLGridData>
        <Bike_Sq>5</Bike_Sq>
        <Bk_Bike_ID>4</Bk_Bike_ID>
        <PT_agency_id>1</PT_agency_id>
        <PT_agency_name>Bikesampa</PT_agency_name>
        <Bk_PL_ID>5</Bk_PL_ID>
        <Bk_Total>12</Bk_Total>
        <Bk_Available>2</Bk_Available>
        <Bk_Last_UPDATE>2016-05-15T19:00:00</Bk_Last_UPDATE>
        <Bk_Active>1</Bk_Active>
        <PL_LT>-2.358947200000000e+001</PL_LT>
        <PL_LG>-4.663995300000000e+001</PL_LG>
        <PL_Desc>BikeSampa -Belas Artes</PL_Desc>
    </XMLGridData>
.....
</response>`

I have checked the data from Alamofire and it is complete.

Could you please help me with this?

**Comment by drmohundro** [comment]
Nothing looks off at first glance, so I don't think I'll be able to help without actually seeing the entire XML content - I'd suggest either putting it in a secret gist (or public if the content can be visible to others).

Some debugging thoughts - are you only getting the first 10 tags, or are they random? If the first 10, is there something in the 11th tag that has odd content? If random, that's especially weird, but it would suggest that maybe some of the content is malformed.

Just some thoughts.

**Comment by GabrielAraujo** [comment]
Thanks for the reply..

After digging and searching a little bit I found that NSXmlParser crashes when it handles special characters in the xml content..

As I'm working with special characters like ç á à and so on what would you recommend? If I change the xml format to some ISO instead of UTF-8 it would process correctly?

**Comment by drmohundro** [comment]
Ahh, gotcha. Yes, I've seen behavior like this before - see #65. I *think* you should be able to just strip any byte order mark unicode values and it should work. The others ones (like ç á à) should be fine I believe.

If it turns out that it is the BOM, then feel free to drop any suggestions on the linked issue. I'd like to resolve it for people using SWXMLHash, but I also feel odd about stripping content.

**Comment by drmohundro** [comment]
I'm going to go ahead and close this one for now, but feel free to comment or re-open if you're still having problems.
