### ISSUE TITLE
Type conversion fails with lazily loaded XML

### ISSUE THREAD

**Issue by adierkens** [drmohundro/SWXMLHash#79]
When using XML parsed with the ```SWXMLHash.lazy()``` method, the type conversion to an array fails with a ```XMLDeserializationError.NodeIsInvalid```

The problem is fixed when changing to ```SWXMLHash.parse()```

**Comment by drmohundro** [comment]
Thanks for the report - I'll see if I can get a test and repro set up for that!

**Comment by drmohundro** [comment]
I just pushed 2.3.2 (both Carthage and CocoaPods) which should resolve this. Thanks again for the report!

**Comment by adierkens** [comment]
Thanks! Just tested it and it works great
