### ISSUE TITLE
API Review before 1.0 release

### ISSUE THREAD

**Issue by drmohundro** [drmohundro/SWXMLHash#8]
The current release is 0.6.0. I want to ensure the API is solid before calling this 1.0 (as I'd like to use semantic versioning). I'd welcome thoughts or suggestions from anyone who makes use of this library, particularly if some method or property names aren't particularly clear.

Some general thoughts:

* Documentation currently refers to a "current level" of indexing (i.e. xml["root"]["header"] is indexing down to "root" and "header"), but this seems vague to me. I'm like to re-think how to describe this.
    * As examples, the `all` and `children` properties behave differently depending on where the code has indexed to.
* Both `all` and `children` might be too vague in their names.

I may consider renaming some methods and properties to help with clarity, but again, I'd welcome input, too.

**Comment by tkrajacic** [comment]
One thing I think would be useful is to be able to access elements using a 'keyPath'.
Maybe something like this (off the top of my hat):
```
func valueFor(key: String) -> XMLIndexer {
        
        let components = key.componentsSeparatedByString(".")
        
        var node = self
        
        for subPath in components {
            node = node[subPath]
            switch node {
            case .Error(let e):
                return node
            default: continue
            }
        }
        return node
    }
```

The second thing that could be useful in the API would be to request an element as a certain type while providing a transformer of (String -> T?).

In any case, thanks for creating this great library!

**Comment by drmohundro** [comment]
Thanks for the comments @tkrajacic! I totally agree regarding the XPath expression - I've thought about that off and on, but hadn't come up with a good way to do it. It might be possible to wrap the existing NSXMLDocument functionality so that XPath support could be added. I've added #9 to track that.

Also, great suggestion on a transformer API... I've experimented with something similar in other projects, but didn't have much success. I've added #10 to track research for that as well.

I wonder if those should be features for 1.0 or if it makes sense to make those additions to the 1.0 release.

**Comment by tkrajacic** [comment]
If those things should be in 1.0 is totally up to you. I think your library works great now, but there will always be stuff to add or improve. I don't think it needs to be in 1.0.

Will add further comments on the features in their respective issues.

**Comment by drmohundro** [comment]
I'll give this issue a week or so to see if other suggestions arise... if nothing else comes out, I'll plan to call the current version 1.0 and then look into a minor version bump for additional features (assuming they don't break API compatibility of course).

**Comment by drmohundro** [comment]
Given that the Xcode 6.3 beta (with Swift 1.2) is out, I'll plan on targeting a 1.0 release with Swift 1.2.

(as a complete aside, this brings up a SemVer question that I hadn't considered before... major versions are supposed to be bumped for breaking changes, but I'm not sure what that means if the underlying framework changes, such as going from Swift 1.1 to Swift 1.2)

**Comment by tkrajacic** [comment]
Yeah it is kind of odd having the language change underneath you that quickly.
Maybe it is better to wait before putting the '1.0' stamp on it until Swift has matured a bit.

After all, this is just a label.

It'll be interesting what Apple will have to say about the future of Swift at WWDC this year.
I think most developers of libraries have that problem at the moment.
Setting up the separate branch for Xcode 6.3 was a great move on your part I think. It is clear, that master is for the non-beta version of Swift, and branches are used for new beta releases of Swift.
I don't even think that anyone needs a library version number in the beta branches. You can't have production code with in anyway. (Well, maybe if you skip the App Store on OS X)

**Comment by drmohundro** [comment]
As lazy loading is now complete and in the xcode-6.3 branch, it will also be part of the 1.0 release.

**Comment by drmohundro** [comment]
1.0.0 is live!
