### ISSUE TITLE
Consider making XMLElement `children` property public

### ISSUE THREAD

**Issue by DanielAsher** [drmohundro/SWXMLHash#82]
I need to iterate over mixed-content xml preserving the order of `XMLElement` / `TextElement`s.

I have found making XMLElement `children` property public allows for this use case.

**Comment by DanielAsher** [comment]
PR #83 includes a unit test for this use case

**Comment by drmohundro** [comment]
Just pushed version `2.4.0` for this pull request. Thanks!
