### ISSUE TITLE
add .all to documentation

### ISSUE THREAD

**Issue by EricWVGG** [drmohundro/SWXMLHash#88]
Took me a few reads to figure out that xml["root"]["catalog"]["book"].all would retrieve "all books under catalog in an array". Maybe I'm dumb.

This is a great tool, thank you.

**Comment by drmohundro** [comment]
Under the ["Returning All Elements At Current Level"](https://github.com/drmohundro/SWXMLHash#returning-all-elements-at-current-level), I've got a small example of it... basically, you can use `for elem in xml["root"]["catalog"]["book"]` *or* `xml["root"]["catalog"]["book"].all`.

I will say that the `.all` method could probably be called out better, though.

(just making sure, is that what you're talking about?)

Thanks!

**Comment by EricWVGG** [comment]
yes, that was how I figured it out… I glossed over the ".map" bit and figured it wasn't what I was looking for. (again, maybe I'm dumb)

**Comment by drmohundro** [comment]
Nahhh, not at all. The current docs hide it behind a sort of obscure call with `.map` after it - it's weird. I'll see about updating it 👍
