### ISSUE TITLE
Type conversion with nested nodes

### ISSUE THREAD

**Issue by olisim** [drmohundro/SWXMLHash#90]
I was wondering if SWXMLHash supports nested nodes of the same type.

Given the following XML:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<nodes>
    <node>
        <name>Dog</name>
        <node>
            <name>Labrador</name>
        </node>
    </node>
    <node>
        <name>Cat</name>
    </node>
    <node>
        <name>Mouse</name>
    </node>
</nodex>
```

And the code:

``` swift
let xml = SWXMLHash.parse(content!)

struct Node: XMLIndexerDeserializable {
    let name: String
    let node: [Node]?

    static func deserialize(node: XMLIndexer) throws -> Node {
        return try Node(
            name: node["name"].value(),
            node: node["node"].value()
        )
    }

}

do {
    let nodes: [Node] = try xml["nodes"]["node"].value()
    print(nodes)
} catch let error {
    print(error)
}
```

This results in the message "This node is invalid: \n".
This is working with child nodes, that are not of type `Node`.

**Comment by drmohundro** [comment]
Interesting, I'll see if I can get a repro set up - I haven't personally tried this, but it *should* work. Just curious, but have you tried it without deserialization?

**Comment by olisim** [comment]
If I try it this way:

```swift
let x = xml["nodes"]["node"].all.map { elem in
    elem["node"]["name"].element?.text
}

print(x)
```

I receive `"[Optional("Labrador"), nil, nil]\n"` as result - seems OK.

**Comment by drmohundro** [comment]
I'm not 100% sure why this doesn't work, but if I introduce another type called `SubNode` to handle the nested nodes, it seems to work for me using the XML you provided.

Like so:

```swift
struct Node: XMLIndexerDeserializable {
    let name: String
    let node: [SubNode]?
    
    static func deserialize(node: XMLIndexer) throws -> Node {
        return try Node(
            name: node["name"].value(),
            node: node["node"].value()
        )
    }
}

struct SubNode: XMLIndexerDeserializable {
    let name: String
    let node: [Node]?
    
    static func deserialize(node: XMLIndexer) throws -> SubNode {
        return try SubNode(
            name: node["name"].value(),
            node: node["node"].value()
        )
    }
}
```

and using the following test:

```swift
func testShouldConvertNestedTypes() {
    let nodes: [Node] = try! parser!["nodes"]["node"].value()
    XCTAssertNotNil(nodes)
}
```

I think it has more to do with the generics aspect of type conversion rather than the parsing, because going through the indexing API seems to work just fine.

I know the workaround isn't ideal, but is this an acceptable approach for the time being? I can keep researching this as well and maybe someone else will have some idea about what is going on.

**Comment by olisim** [comment]
Sadly this is no workaround for me because I'm consuming an provided web service that has a structure like the example.
It seems that the type conversion is failing on the first node that has no same-named child nodes. It's working if the nodes are named differently. Curious...  Maybe you find a solution for this problem eventually, I would appreciate it very much.

**Comment by benjyspider** [comment]
Here is an issue on nested nodes ? Another question can we use objects instead of structs ?

**Comment by drmohundro** [comment]
@benjyspider not sure I'm following your line of questioning - are you asking if deserialization works with classes instead of structs? If so, I'd suggest opening a new issue to keep that question separate.

**Comment by drmohundro** [comment]
Given that there hasn't been activity on this issue in _eight_ years, I'm closing this issue. 🧓🏻 

(I'm almost afraid to close it in the event that it drops notifications on this)
