### ISSUE TITLE
什么时候会有支持Swift 3.0的版本？！

### ISSUE THREAD

**Issue by noear** [drmohundro/SWXMLHash#91]
太需要了！！！

**Comment by noear** [comment]
我最新的项目正是用 Swift 3.0 + XCode 8.0 开发的

**Comment by drmohundro** [comment]
(for my own reference, [Google Translate](https://translate.google.com/?um=1&ie=UTF-8&hl=en&client=tw-ob#zh-CN/en/%E6%88%91%E6%9C%80%E6%96%B0%E7%9A%84%E9%A1%B9%E7%9B%AE%E6%AD%A3%E6%98%AF%E7%94%A8%20Swift%203.0%20%20%20XCode%208.0%20%E5%BC%80%E5%8F%91%E7%9A%84))

Title: "When there will be support for Swift 3.0 version"

Body: "My latest project is with Swift 3.0 + XCode 8.0 development"

Check out the [xcode-8.0 branch](https://github.com/drmohundro/SWXMLHash/tree/xcode-8.0) branch (with corresponding PR #78). I'm not planning to release this to mainline until Xcode 8.0 hits the AppStore; however, you can pull that branch down and it should work just fine for Swift 3.0.

Hope this helps!
