### ISSUE TITLE
什么支持XCode 8.0 + Swift 3.0 ？！

### ISSUE THREAD

**Issue by noear** [drmohundro/SWXMLHash#93]
实在是太需要了！！！

**Comment by drmohundro** [comment]
I already responded to your last issue (see #91). It is all on the [xcode-8.0 branch](https://github.com/drmohundro/SWXMLHash/tree/xcode-8.0).

我已经回答了你的最后一个问题（见＃91）。这是所有在XCode8.0分支。

(translations thanks to Google Translate)

**Comment by noear** [comment]
太感谢你了。我之前发的那条，找不到了；还以为我未发过。。。谢谢。

**Comment by drmohundro** [comment]
我很乐意帮助！它将在的CocoaPods被释放时的Xcode8显示了在App Store上。
