### ISSUE TITLE
Carthage build error in Xcode8 & Swift2.3 

### ISSUE THREAD

**Issue by kirou** [drmohundro/SWXMLHash#94]
Hi.

I tried Carthage build in Xcode 8 & Swift2.3.
However Carthage build error.

> Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for  targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

Use Legacy Swift Language Version is Unspecified
> Build Settings > Use Legacy Swift Language Version > Unspecified.

I would appreciate this value changed YES in Somewhere branch.

I would be grateful if you would kindly consider it.

**Comment by drmohundro** [comment]
Hi @kirou - I just merged #95 which should resolve this. Could you check it out and see if it fixes it for you? I tagged `2.5.1` with these changes so Carthage should be able to pick it up.

**Comment by kirou** [comment]
I am sorry for the late reply.

I tried the build, was successful without any problems.

Thank you!

**Comment by drmohundro** [comment]
Great, thanks for the follow up @kirou!
