### ISSUE TITLE
is that possible to support ios 8 ?

### ISSUE THREAD

**Issue by romk1n** [drmohundro/SWXMLHash#99]
We are still not ready to drop this support and too many pods depend on you :)

**Comment by drmohundro** [comment]
I apologize about that @romk1n - when I was trying to push out the original 3.0.0 release, I was getting errors and I inadvertently published a version that restricted the iOS release to 9.0.

I just pushed `3.0.2` which allows for iOS 8.0 again. Let me know if that works for you.

And thanks for the report!

**Comment by colditz18** [comment]
How can I get that 3.0.2 version for iOS8 through cocoaPods?? Thanks

**Comment by drmohundro** [comment]
@colditz18 what does your `Podfile` look like?

It should probably look something like:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target '<Your Target Name>' do
    pod 'SWXMLHash', '~> 3.0.0'
end
```

**Comment by colditz18** [comment]
using that I get the error
[!] Unable to satisfy the following requirements:

- `SWXMLHash (~> 3.0.0)` required by `Podfile`

Specs satisfying the `SWXMLHash (~> 3.0.0)` dependency were found, but they required a higher minimum deployment target.

I dont know if it's because of the pod itself or because of the CocoaPods configuration...

**Comment by gca3020** [comment]
Try specifying '3.0' not '3.0.0', which should cause CocoaPods' Semantic Parser to pull version 3.0.X where 'X' is the most recent. 

Alternately, you could specify '3.0.2' explicitly, but then you wouldn't get automatic updates when version 3.0.3 is pushed. 

If you want it to automatically update to any 3.X release (presumably the API-breaking changes will happen with v4, you should just specify '3' in the Podfile.

**Comment by colditz18** [comment]
same error with 3.0 instead of 3.0.0

**Comment by colditz18** [comment]
somehow I got it to work by using pod update, instead of install. Thank you

**Comment by drmohundro** [comment]
Great, thanks for the update @colditz18! I'll close, but please re-open if you continue to see issues!
